export const sample = [
    {
        OrgUnitId: 1230,
        OrgUnitDisplayName: 'Hoops Stop-KS',
        LegalEntityId: 6,
        LegalEntityDisplayName: 'LE Pro Shop',
        DeptJobId: 1,
        DeptJobDisplayName: 'Store - Store Manager',
        PositionDepartmentName: 'Store - Store Manager (Store)',
        DepartmentDisplayName: 'Store',
    },
    {
        OrgUnitId: 1212,
        OrgUnitDisplayName: 'Surf Wax-DE',
        LegalEntityId: 6,
        LegalEntityDisplayName: 'LE Pro Shop',
        DeptJobId: 1,
        DeptJobDisplayName: 'Store - Store Manager',
        PositionDepartmentName: 'Store - Store Manager (Store)',
        DepartmentDisplayName: 'Store',
    },
    {
        OrgUnitId: 1163,
        OrgUnitDisplayName: 'Sharpening-NY',
        LegalEntityId: 6,
        LegalEntityDisplayName: 'LE Pro Shop',
        DeptJobId: 2,
        DeptJobDisplayName: 'Store Asst. Manager',
        PositionDepartmentName: 'Store Asst. Manager (Store)',
        DepartmentDisplayName: 'Store',
    },
    {
        OrgUnitId: 1349,
        OrgUnitDisplayName: 'Alaska  ONSITE',
        LegalEntityId: 11,
        LegalEntityDisplayName: 'LE US',
        DeptJobId: 23,
        DeptJobDisplayName: 'President',
        PositionDepartmentName: 'President (Store)',
        DepartmentDisplayName: 'Store',
    },
];
