import {CheckTemplateConstants} from "../../constant/constant.js";

const templates = [
    {
        payRunDefId: 1,
        shortName: CheckTemplateConstants.CODE_NAME_NORMAL,
        xrefCode: 'NORMAL',
        isNormal: true,
        isManual: false,
        isManualSystemDefault: false,
        isSystemDefault: false,
        isNormalSystemDefault: false,
        isOffCycleSystemDefault: false,
        employementType: 'Employee',
        applyDeceasedTaxation: false,
        isCovid19Template: false,
        isERetentionTemplate: false,
        specialPayType: 0,
    },
    {
        payRunDefId: 2,
        shortName: 'Manual',
        xrefCode: CheckTemplateConstants.CODE_NAME_MANUAL,
        isNormal: false,
        isManual: false,
        isManualSystemDefault: true,
        isSystemDefault: false,
        isNormalSystemDefault: false,
        isOffCycleSystemDefault: false,
        employementType: 'Employee',
        applyDeceasedTaxation: false,
        isCovid19Template: false,
        isERetentionTemplate: false,
        specialPayType: 0,
    },
    {
        payRunDefId: 3,
        shortName: 'Additional',
        xrefCode: CheckTemplateConstants.CODE_NAME_ADDITIONAL,
        isNormal: false,
        isManual: false,
        isManualSystemDefault: false,
        isSystemDefault: false,
        isNormalSystemDefault: false,
        isOffCycleSystemDefault: false,
        employementType: 'Employee',
        applyDeceasedTaxation: false,
        isCovid19Template: false,
        isERetentionTemplate: false,
        specialPayType: 0,
    },
    {
        payRunDefId: 4,
        shortName: 'Off Cycle',
        xrefCode: CheckTemplateConstants.CODE_NAME_OFF_CYCLE,
        isNormal: false,
        isManual: false,
        isManualSystemDefault: false,
        isSystemDefault: false,
        isNormalSystemDefault: false,
        isOffCycleSystemDefault: false,
        employementType: 'Employee',
        applyDeceasedTaxation: false,
        isCovid19Template: false,
        isERetentionTemplate: false,
        specialPayType: 0,
    },
    {
        payRunDefId: 5,
        shortName: 'Pensioner',
        xrefCode: CheckTemplateConstants.CODE_NAME_PENSIONER,
        isNormal: false,
        isManual: false,
        isManualSystemDefault: false,
        isSystemDefault: false,
        isNormalSystemDefault: false,
        isOffCycleSystemDefault: false,
        employementType: 'Pensioner',
        applyDeceasedTaxation: false,
        isCovid19Template: false,
        isERetentionTemplate: false,
        specialPayType: 0,
    },
    {
        payRunDefId: 6,
        shortName: 'Deceased',
        xrefCode: CheckTemplateConstants.CODE_NAME_DECEASED,
        isNormal: false,
        isManual: false,
        isManualSystemDefault: false,
        isSystemDefault: false,
        isNormalSystemDefault: false,
        isOffCycleSystemDefault: false,
        employementType: 'Employee',
        applyDeceasedTaxation: true,
        isCovid19Template: false,
        isERetentionTemplate: false,
        specialPayType: 0,
    },
    {
        payRunDefId: 7,
        shortName: 'Advance Pay',
        xrefCode: CheckTemplateConstants.CODE_NAME_ADVANCE_PAY,
        isNormal: false,
        isManual: false,
        isManualSystemDefault: false,
        isSystemDefault: false,
        isNormalSystemDefault: false,
        isOffCycleSystemDefault: false,
        employementType: 'Employee',
        applyDeceasedTaxation: true,
        isCovid19Template: false,
        isERetentionTemplate: false,
        specialPayType: 1,
    },
    {
        payRunDefId: 8,
        shortName: 'Retro Pay',
        xrefCode: CheckTemplateConstants.CODE_NAME_RETRO_PAY,
        isNormal: false,
        isManual: false,
        isManualSystemDefault: false,
        isSystemDefault: false,
        isNormalSystemDefault: false,
        isOffCycleSystemDefault: false,
        employementType: 'Employee',
        applyDeceasedTaxation: true,
        isCovid19Template: false,
        isERetentionTemplate: false,
        specialPayType: 2,
    },
];


export const getCheckTemplates = ()=>{
    return templates
}