import {CodeTypeEnum, ProcessForEmploymentTypeEnum} from "../../constant/constant.js";


const earningCodeTemplate = {
    codeTypeId: CodeTypeEnum.Earning,
    isActive: true,
    codeId: null,
    shortName: null,
    uniqueId: null,
    defaultCheckTypeId: null,
    isHoursRateInPayEntryEnabled: null,
    isHoursRateInPayEntryErrorOverride: null,
    isGenerated: null,
    isWcbDeduction: null,
    isFlsaAdjustable: null,
    processForEmployment: null,
    isEmployerDeduction: null,
    payoutBalanceId: null,
    earningTaxability: null,
    earningTypeCodeName: null,
    allowImpromptuArrears: null,
    debitArrearsByDefault: null,
    allowPayee: null,
    isPayEntryWageAttachment: null,
    isInternal: null,
    useInPayrollEntry: null,
};

export const EarningCodes  = [
    {
        ...earningCodeTemplate,
        codeId: 1,
        shortName: 'Holiday',
        uniqueId: '1-1',
        defaultCheckTypeId: 1,
        isHoursRateInPayEntryEnabled: true,
        isHoursRateInPayEntryErrorOverride: false,
        isGenerated: false,
        isFlsaAdjustable: false,
        processForEmployment: ProcessForEmploymentTypeEnum.REGULAR,
        earningTaxability: 'BSIE035',
    },
    {
        ...earningCodeTemplate,
        codeId: 2,
        shortName: 'Bonus',
        uniqueId: '1-2',
        isHoursRateInPayEntryEnabled: false,
        isHoursRateInPayEntryErrorOverride: false,
        isGenerated: false,
        processForEmployment: ProcessForEmploymentTypeEnum.REGULAR,
        payoutBalanceId: 1,
        isFlsaAdjustable: true,
        allowPayee: true,
    },
    {
        ...earningCodeTemplate,
        codeId: 3,
        shortName: 'Salary UK',
        uniqueId: '1-3',
        isHoursRateInPayEntryEnabled: true,
        isHoursRateInPayEntryErrorOverride: false,
        isGenerated: true,
        processForEmployment: ProcessForEmploymentTypeEnum.REGULAR,
        isFlsaAdjustable: false,
    },
    {
        ...earningCodeTemplate,
        codeId: 4,
        shortName: 'Apprentice Tax Levy',
        uniqueId: '1-4',
        isGenerated: false,
        processForEmployment: ProcessForEmploymentTypeEnum.REGULAR,
        isFlsaAdjustable: false,
    },
    {
        ...earningCodeTemplate,
        codeId: 5,
        shortName: 'Regular',
        uniqueId: '1-5',
        defaultCheckTypeId: 1,
        isHoursRateInPayEntryEnabled: true,
        isHoursRateInPayEntryErrorOverride: false,
        isGenerated: false,
        isFlsaAdjustable: true,
        allowPayee: true,
    },
    {
        ...earningCodeTemplate,
        codeId: 6,
        shortName: 'EW',
        uniqueId: '1-6',
        isHoursRateInPayEntryEnabled: false,
        isHoursRateInPayEntryErrorOverride: false,
        isGenerated: false,
        processForEmployment: ProcessForEmploymentTypeEnum.REGULAR,
        isFlsaAdjustable: false,
    },
    {
        ...earningCodeTemplate,
        codeId: 7,
        shortName: 'Overtime',
        uniqueId: '1-7',
        isHoursRateInPayEntryEnabled: true,
        isHoursRateInPayEntryErrorOverride: false,
        isGenerated: true,
        processForEmployment: ProcessForEmploymentTypeEnum.REGULAR,
        isFlsaAdjustable: false,
    },
    {
        ...earningCodeTemplate,
        codeId: 8,
        shortName: 'Insurance',
        uniqueId: '1-8',
        isGenerated: false,
        processForEmployment: ProcessForEmploymentTypeEnum.REGULAR,
        isFlsaAdjustable: false,
    },
    {
        ...earningCodeTemplate,
        uniqueId: '1-74',
        codeId: 74,
        shortName: '3rd Party Sick Non-taxable',
        isHoursRateInPayEntryEnabled: false,
        isHoursRateInPayEntryErrorOverride: false,
        isGenerated: false,
        processForEmployment: ProcessForEmploymentTypeEnum.NONE,
        isFlsaAdjustable: false,
        allowPayee: false,
        isPayEntryWageAttachment: false,
        earningTaxability: 'BSIE037',
    },
    {
        ...earningCodeTemplate,
        uniqueId: '1-75',
        codeId: 75,
        shortName: '3rd Party Sick Taxable',
        isHoursRateInPayEntryEnabled: false,
        isHoursRateInPayEntryErrorOverride: false,
        isGenerated: false,
        processForEmployment: ProcessForEmploymentTypeEnum.NONE,
        isFlsaAdjustable: false,
        allowPayee: false,
        isPayEntryWageAttachment: false,
        earningTaxability: 'BSIE037',
    },
    {
        ...earningCodeTemplate,
        codeId: 76,
        shortName: '*OnDemand',
        uniqueId: '1-76',
        isHoursRateInPayEntryEnabled: false,
        isHoursRateInPayEntryErrorOverride: false,
        isGenerated: false,
        processForEmployment: ProcessForEmploymentTypeEnum.REGULAR,
        payoutBalanceId: 1,
        isFlsaAdjustable: false,
        allowPayee: true,
        isInternal: true,
    },
];