import { CodeTypeEnum } from '@models/enums/CodeTypeEnum';
import { CodeType, TaxCodeType } from '@models/code/CodeTypes';

const taxCodeTemplate: TaxCodeType & CodeType = {
    codeTypeId: CodeTypeEnum.Tax,
    isActive: true,
    uniqueId: null,
    codeId: null,
    shortName: null,
    effectiveEnd: null,
    effectiveStart: '2011-01-01T00:00:00',
    isTaxUnSupported: false,
    payrollTaxLegalEntityIds: [4, 3, 2, 5, 6, 11],
    notSupportedTaxInstanceItems: null,
    isEmployerTax: false,
    taxCategoryId: null,
    taxAuthorityInstanceId: null,

    isWcbDeduction: null,
    isGenerated: null,
    defaultCheckTypeId: null,
    processForEmployment: null,
    isHoursRateInPayEntryEnabled: null,
    isHoursRateInPayEntryErrorOverride: null,
    isPayEntryWageAttachment: null,
    countryCode: null,
    employeeId: null,
    isInternal: null,
    useInPayrollEntry: null,
};

export const TaxCodes: Array<TaxCodeType> = [
    {
        ...taxCodeTemplate,
        uniqueId: '3-1',
        codeId: 1,
        shortName: 'USA-00250000-092',
        taxCategoryId: 'USA-092',
        taxAuthorityInstanceId: 'USA-00250000-092',
    },
    {
        ...taxCodeTemplate,
        uniqueId: '3-2',
        codeId: 2,
        shortName: 'USA-00340000-010',
        taxCategoryId: 'USA-010',
        taxAuthorityInstanceId: 'USA-00340000-010',
    },
    {
        ...taxCodeTemplate,
        uniqueId: '3-3',
        codeId: 3,
        shortName: 'CAN-10140000-05',
        taxCategoryId: 'CAN-05',
        taxAuthorityInstanceId: 'CAN-10140000-05',
    },
    {
        ...taxCodeTemplate,
        uniqueId: '3-4',
        codeId: 4,
        codeTypeId: CodeTypeEnum.Tax,
        shortName: 'CAN-10140000-06',
        taxCategoryId: 'CAN-06',
        taxAuthorityInstanceId: 'CAN-10140000-06',
    },
    {
        ...taxCodeTemplate,
        uniqueId: '3-5',
        codeId: 5,
        shortName: 'CAN-10000000-01',
        taxCategoryId: 'CAN-01',
        taxAuthorityInstanceId: 'CAN-10000000-01',
    },
    {
        ...taxCodeTemplate,
        uniqueId: '3-6',
        codeId: 6,
        shortName: 'CAN-10000000-03',
        taxCategoryId: 'CAN-03',
        taxAuthorityInstanceId: 'CAN-10000000-03',
    },
    {
        ...taxCodeTemplate,
        uniqueId: '3-7',
        codeId: 7,
        shortName: 'CAN-10000000-01',
        taxCategoryId: 'CAN-01',
        taxAuthorityInstanceId: 'CAN-10000000-01',
    },
    {
        ...taxCodeTemplate,
        uniqueId: '3-8',
        codeId: 8,
        shortName: 'USA-00250000-018',
        taxCategoryId: 'USA-018',
        taxAuthorityInstanceId: 'USA-00250000-018',
    },
];
