import { EmployeePreviewType } from '@models/preview/EmployeePreviewSummaryType';

export const employeePreviews: EmployeePreviewType[] = [
    {
        employeeId: 1,
        employeeName: 'Amélie Lacroix',
        employeeNumber: 'IL0002',
        items: [
            {
                previewItemLevel: 0,
                modelId: 0,
                itemType: 0,
                modelType: 1,
                currentAmount: 19171,
                toCompareCurrentAmount: null,
                currentAmountVariance: 19171,
                currentHours: 265,
                toCompareCurrentHours: null,
                currentHoursVariance: 265,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: 9350,
                ytdAmount: 71975.68,
                qtdAmount: 42044.19,
            },
            {
                previewItemLevel: 1,
                modelId: 1,
                itemType: 0,
                modelType: 1,
                currentAmount: 9800,
                toCompareCurrentAmount: null,
                currentAmountVariance: 9800,
                currentHours: 255,
                toCompareCurrentHours: null,
                currentHoursVariance: 255,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: 6200,
                ytdAmount: 49335.5,
                qtdAmount: 20940,
            },
            {
                previewItemLevel: 1,
                modelId: 2,
                itemType: 0,
                modelType: 1,
                currentAmount: null,
                toCompareCurrentAmount: null,
                currentAmountVariance: null,
                currentHours: null,
                toCompareCurrentHours: null,
                currentHoursVariance: null,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: 1250,
                ytdAmount: 3250,
                qtdAmount: 3250,
            },
            {
                previewItemLevel: 1,
                modelId: 3,
                itemType: 0,
                modelType: 1,
                currentAmount: 50,
                toCompareCurrentAmount: null,
                currentAmountVariance: 50,
                currentHours: null,
                toCompareCurrentHours: null,
                currentHoursVariance: null,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: 100,
                ytdAmount: 300,
                qtdAmount: 300,
            },
            {
                previewItemLevel: 1,
                modelId: 4,
                itemType: 0,
                modelType: 1,
                currentAmount: 2955,
                toCompareCurrentAmount: null,
                currentAmountVariance: 2955,
                currentHours: 10,
                toCompareCurrentHours: null,
                currentHoursVariance: 10,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: 1500,
                ytdAmount: 7503.2,
                qtdAmount: 6003.2,
            },
            {
                previewItemLevel: 1,
                modelId: 5,
                itemType: 0,
                modelType: 1,
                currentAmount: 1680.5,
                toCompareCurrentAmount: null,
                currentAmountVariance: 1680.5,
                currentHours: null,
                toCompareCurrentHours: null,
                currentHoursVariance: null,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: 0,
                ytdAmount: 11250.99,
                qtdAmount: 11250.99,
            },
            {
                previewItemLevel: 1,
                modelId: 6,
                itemType: 0,
                modelType: 1,
                currentAmount: 3545,
                toCompareCurrentAmount: null,
                currentAmountVariance: null,
                currentHours: null,
                toCompareCurrentHours: null,
                currentHoursVariance: null,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: 300,
                ytdAmount: 300,
                qtdAmount: 300,
            },
            {
                previewItemLevel: 1,
                modelId: 7,
                itemType: 0,
                modelType: 1,
                currentAmount: 4643,
                toCompareCurrentAmount: null,
                currentAmountVariance: null,
                currentHours: null,
                toCompareCurrentHours: null,
                currentHoursVariance: null,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: 0,
                ytdAmount: 35.99,
                qtdAmount: 0,
            },
            {
                previewItemLevel: 0,
                modelId: 0,
                itemType: 7,
                modelType: 2,
                currentAmount: 634.5,
                toCompareCurrentAmount: null,
                currentAmountVariance: 634.5,
                currentHours: null,
                toCompareCurrentHours: null,
                currentHoursVariance: null,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: 998,
                ytdAmount: 2191.5,
                qtdAmount: 1960,
            },
            {
                previewItemLevel: 1,
                modelId: 1,
                itemType: 7,
                modelType: 2,
                currentAmount: 50,
                toCompareCurrentAmount: null,
                currentAmountVariance: 50,
                currentHours: null,
                toCompareCurrentHours: null,
                currentHoursVariance: null,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: 100,
                ytdAmount: 450,
                qtdAmount: 300,
            },
            {
                previewItemLevel: 1,
                modelId: 2,
                itemType: 7,
                modelType: 2,
                currentAmount: 25,
                toCompareCurrentAmount: null,
                currentAmountVariance: 25,
                currentHours: null,
                toCompareCurrentHours: null,
                currentHoursVariance: null,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: 175,
                ytdAmount: 350,
                qtdAmount: 305,
            },
            {
                previewItemLevel: 1,
                modelId: 3,
                itemType: 7,
                modelType: 2,
                currentAmount: 8,
                toCompareCurrentAmount: null,
                currentAmountVariance: 8,
                currentHours: null,
                toCompareCurrentHours: null,
                currentHoursVariance: null,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: 16,
                ytdAmount: 72,
                qtdAmount: 48,
            },
            {
                previewItemLevel: 1,
                modelId: 4,
                itemType: 7,
                modelType: 2,
                currentAmount: 539,
                toCompareCurrentAmount: null,
                currentAmountVariance: 539,
                currentHours: null,
                toCompareCurrentHours: null,
                currentHoursVariance: null,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: 682,
                ytdAmount: 1232,
                qtdAmount: 1232,
            },
            {
                previewItemLevel: 1,
                modelId: 5,
                itemType: 7,
                modelType: 2,
                currentAmount: 12.5,
                toCompareCurrentAmount: null,
                currentAmountVariance: 12.5,
                currentHours: null,
                toCompareCurrentHours: null,
                currentHoursVariance: null,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: 25,
                ytdAmount: 87.5,
                qtdAmount: 75,
            },
            {
                previewItemLevel: 0,
                modelId: 0,
                itemType: 10,
                modelType: 3,
                currentAmount: 0,
                toCompareCurrentAmount: null,
                currentAmountVariance: 0,
                currentHours: null,
                toCompareCurrentHours: null,
                currentHoursVariance: null,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: 0,
                currentTotalTaxableWages: 38142,
                mtdAmount: 0,
                ytdAmount: 0,
                qtdAmount: 0,
            },
            {
                previewItemLevel: 1,
                modelId: 1,
                itemType: 10,
                modelType: 3,
                currentAmount: 786.45,
                toCompareCurrentAmount: null,
                currentAmountVariance: null,
                currentHours: null,
                toCompareCurrentHours: null,
                currentHoursVariance: null,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: 0,
                ytdAmount: 0,
                qtdAmount: 0,
            },
            {
                previewItemLevel: 1,
                modelId: 2,
                itemType: 10,
                modelType: 3,
                currentAmount: 34.78,
                toCompareCurrentAmount: null,
                currentAmountVariance: null,
                currentHours: null,
                toCompareCurrentHours: null,
                currentHoursVariance: null,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: 0,
                ytdAmount: 0,
                qtdAmount: 0,
            },
            {
                previewItemLevel: 1,
                modelId: 3,
                itemType: 10,
                modelType: 3,
                currentAmount: 345.88,
                toCompareCurrentAmount: null,
                currentAmountVariance: null,
                currentHours: null,
                toCompareCurrentHours: null,
                currentHoursVariance: null,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: 0,
                ytdAmount: 0,
                qtdAmount: 0,
            },
            {
                previewItemLevel: 1,
                modelId: 4,
                itemType: 10,
                modelType: 3,
                currentAmount: null,
                toCompareCurrentAmount: null,
                currentAmountVariance: null,
                currentHours: null,
                toCompareCurrentHours: null,
                currentHoursVariance: null,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: 0,
                ytdAmount: 0,
                qtdAmount: 0,
            },
            {
                previewItemLevel: 0,
                modelId: 0,
                itemType: 11,
                modelType: 3,
                currentAmount: 0,
                toCompareCurrentAmount: null,
                currentAmountVariance: 0,
                currentHours: null,
                toCompareCurrentHours: null,
                currentHoursVariance: null,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: 0,
                currentTotalTaxableWages: 0,
                mtdAmount: 0,
                ytdAmount: 0,
                qtdAmount: 0,
            },
            {
                previewItemLevel: 1,
                modelId: 1,
                itemType: 11,
                modelType: 3,
                currentAmount: 12,
                toCompareCurrentAmount: null,
                currentAmountVariance: 12,
                currentHours: null,
                toCompareCurrentHours: null,
                currentHoursVariance: null,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: 0,
                ytdAmount: 0,
                qtdAmount: 0,
            },
            {
                previewItemLevel: 1,
                modelId: 2,
                itemType: 11,
                modelType: 3,
                currentAmount: null,
                toCompareCurrentAmount: null,
                currentAmountVariance: null,
                currentHours: null,
                toCompareCurrentHours: null,
                currentHoursVariance: null,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: 0,
                ytdAmount: 0,
                qtdAmount: 0,
            },
            {
                previewItemLevel: 1,
                modelId: 3,
                itemType: 11,
                modelType: 3,
                currentAmount: null,
                toCompareCurrentAmount: null,
                currentAmountVariance: null,
                currentHours: null,
                toCompareCurrentHours: null,
                currentHoursVariance: null,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: 0,
                ytdAmount: 0,
                qtdAmount: 0,
            },
            {
                previewItemLevel: 1,
                modelId: 4,
                itemType: 11,
                modelType: 3,
                currentAmount: null,
                toCompareCurrentAmount: null,
                currentAmountVariance: null,
                currentHours: null,
                toCompareCurrentHours: null,
                currentHoursVariance: null,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: 0,
                ytdAmount: 0,
                qtdAmount: 0,
            },
            {
                previewItemLevel: 1,
                modelId: 5,
                itemType: 10,
                modelType: 3,
                currentAmount: null,
                toCompareCurrentAmount: null,
                currentAmountVariance: null,
                currentHours: null,
                toCompareCurrentHours: null,
                currentHoursVariance: null,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: 0,
                ytdAmount: 0,
                qtdAmount: 0,
            },
            {
                previewItemLevel: 1,
                modelId: 6,
                itemType: 10,
                modelType: 3,
                currentAmount: null,
                toCompareCurrentAmount: null,
                currentAmountVariance: null,
                currentHours: null,
                toCompareCurrentHours: null,
                currentHoursVariance: null,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: 0,
                ytdAmount: 0,
                qtdAmount: 0,
            },
            {
                previewItemLevel: 1,
                modelId: 7,
                itemType: 11,
                modelType: 3,
                currentAmount: null,
                toCompareCurrentAmount: null,
                currentAmountVariance: null,
                currentHours: null,
                toCompareCurrentHours: null,
                currentHoursVariance: null,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: 0,
                ytdAmount: 0,
                qtdAmount: 0,
            },
            {
                previewItemLevel: 1,
                modelId: 8,
                itemType: 7,
                modelType: 2,
                currentAmount: null,
                toCompareCurrentAmount: null,
                currentAmountVariance: null,
                currentHours: null,
                toCompareCurrentHours: null,
                currentHoursVariance: null,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: 0,
                ytdAmount: 0,
                qtdAmount: 0,
            },
            {
                previewItemLevel: 1,
                modelId: 9,
                itemType: 7,
                modelType: 2,
                currentAmount: null,
                toCompareCurrentAmount: null,
                currentAmountVariance: null,
                currentHours: null,
                toCompareCurrentHours: null,
                currentHoursVariance: null,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: 0,
                ytdAmount: 0,
                qtdAmount: 0,
            },
            {
                previewItemLevel: 1,
                modelId: 10,
                itemType: 7,
                modelType: 2,
                currentAmount: null,
                toCompareCurrentAmount: null,
                currentAmountVariance: null,
                currentHours: null,
                toCompareCurrentHours: null,
                currentHoursVariance: null,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: 0,
                ytdAmount: 0,
                qtdAmount: 0,
            },
            {
                previewItemLevel: 1,
                modelId: 11,
                itemType: 7,
                modelType: 2,
                currentAmount: null,
                toCompareCurrentAmount: null,
                currentAmountVariance: null,
                currentHours: null,
                toCompareCurrentHours: null,
                currentHoursVariance: null,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: 0,
                ytdAmount: 0,
                qtdAmount: 0,
            },
            {
                previewItemLevel: 0,
                modelId: 0,
                itemType: 12,
                modelType: 0,
                currentAmount: null,
                toCompareCurrentAmount: null,
                currentAmountVariance: null,
                currentHours: null,
                toCompareCurrentHours: null,
                currentHoursVariance: null,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: null,
                ytdAmount: null,
                qtdAmount: null,
            },
            {
                previewItemLevel: 1,
                modelId: 999,
                itemType: 12,
                modelType: 0,
                currentAmount: null,
                toCompareCurrentAmount: null,
                currentAmountVariance: null,
                currentHours: null,
                toCompareCurrentHours: null,
                currentHoursVariance: null,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: null,
                ytdAmount: null,
                qtdAmount: null,
            },
            {
                previewItemLevel: 1,
                modelId: 9999,
                itemType: 12,
                modelType: 0,
                currentAmount: null,
                toCompareCurrentAmount: null,
                currentAmountVariance: null,
                currentHours: null,
                toCompareCurrentHours: null,
                currentHoursVariance: null,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: null,
                ytdAmount: null,
                qtdAmount: null,
            },
            {
                previewItemLevel: 0,
                modelId: 0,
                itemType: 3,
                modelType: 1,
                currentAmount: 12.35,
                toCompareCurrentAmount: null,
                currentAmountVariance: 12.35,
                currentHours: null,
                toCompareCurrentHours: null,
                currentHoursVariance: null,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: 0,
                ytdAmount: 37.05,
                qtdAmount: 0,
            },
            {
                previewItemLevel: 1,
                modelId: 1,
                itemType: 3,
                modelType: 1,
                currentAmount: 12.35,
                toCompareCurrentAmount: null,
                currentAmountVariance: 12.35,
                currentHours: null,
                toCompareCurrentHours: null,
                currentHoursVariance: null,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: 0,
                ytdAmount: 37.05,
                qtdAmount: 0,
            },
        ],
    },
    {
        employeeId: 2,
        employeeName: 'Hana Song',
        employeeNumber: 'IL0002',
        items: [
            {
                previewItemLevel: 0,
                modelId: 0,
                itemType: 0,
                modelType: 1,
                currentAmount: 19171,
                toCompareCurrentAmount: null,
                currentAmountVariance: 19171,
                currentHours: 265,
                toCompareCurrentHours: null,
                currentHoursVariance: 265,
                adjustmentAmount: null,
                adjustmentHours: null,
                currentLimitedTaxableWages: null,
                currentTotalTaxableWages: null,
                mtdAmount: 9350,
                ytdAmount: 71975.68,
                qtdAmount: 42044.19,
            },
        ],
    },
];
