import { ApiPagingDataType } from '@models/common/ApiResultTypes';
import { AuditItem } from '@models/reports';
import { applyPagination, applySearch } from '@utils/DataUtils';

export const getMockAuditItems = (
    skip: number,
    take: number,
    searchTerm: string
): ApiPagingDataType<AuditItem> => {
    const filteredItems = applySearch(mockAuditItems, searchTerm, [
        'name',
    ]).sort((a, b) => a.name.localeCompare(b.name));

    const paginatedItems = applyPagination(filteredItems, skip, take);
    return {
        totalCount: filteredItems.length,
        items: paginatedItems,
    };
};

export const mockAuditItems: AuditItem[] = [
    {
        featureId: 1,
        reportDefinitionId: 101,
        reportUniqueId: null,
        name: 'Invalid SSN-SIN',
        description: 'Employees with Invalid SSN-SIN',
        isCustomReport: false,
        clientId: 0,
        createdUserId: 0,
    },
    {
        featureId: 2,
        reportDefinitionId: 102,
        reportUniqueId: null,
        name: 'Negative Earnings',
        description: 'Employees with Negative Earnings',
        isCustomReport: false,
        clientId: 0,
        createdUserId: 0,
    },
    {
        featureId: 3,
        reportDefinitionId: 103,
        reportUniqueId: null,
        name: 'Negative Deductions',
        description: 'Employees with Negative Deductions',
        isCustomReport: false,
        clientId: 0,
        createdUserId: 0,
    },
    {
        featureId: 4,
        reportDefinitionId: null,
        reportUniqueId: null,
        name: 'Inactive Employees',
        description: 'Inactive Employees from this Pay Run',
        isCustomReport: false,
        clientId: 0,
        createdUserId: 0,
    },
    {
        featureId: 5,
        reportDefinitionId: 105,
        reportUniqueId: null,
        name: 'Terminated Employees',
        description: 'Terminated Employees from this Pay Run',
        isCustomReport: false,
        clientId: 0,
        createdUserId: 0,
    },
    {
        featureId: 6,
        reportDefinitionId: 106,
        reportUniqueId: null,
        name: 'Zero Dollar Checks',
        description: 'Employees with a Zero Dollar Check',
        isCustomReport: false,
        clientId: 0,
        createdUserId: 0,
    },
    {
        featureId: 7,
        reportDefinitionId: 107,
        reportUniqueId: null,
        name: 'Negative Total Taxes',
        description: 'Employees with Negative Total Taxes',
        isCustomReport: false,
        clientId: 0,
        createdUserId: 0,
    },
    {
        featureId: 8,
        reportDefinitionId: 108,
        reportUniqueId: null,
        name: 'Duplicate Bank Accounts',
        description: 'Bank accounts receiving payments for multiple employees.',
        isCustomReport: false,
        clientId: 0,
        createdUserId: 0,
    },
    {
        featureId: 9,
        reportDefinitionId: 109,
        reportUniqueId: null,
        name: 'Employee Primary Address Change',
        description: 'Changes made to Employee Address in Pay Run',
        isCustomReport: false,
        clientId: 0,
        createdUserId: 0,
    },
    {
        featureId: 10,
        reportDefinitionId: null,
        reportUniqueId: null,
        name: 'Employees earning less than minimum statutory salary',
        description:
            'Report containing list of employees earning less than the current minimum statutory salary in Mauritius',
        isCustomReport: false,
        clientId: 1086,
        createdUserId: null,
    },
    {
        featureId: 11,
        reportDefinitionId: 111,
        reportUniqueId: null,
        name: 'Deductions Not Taken',
        description: 'Deductions Not Taken',
        isCustomReport: false,
        clientId: 0,
        createdUserId: 0,
    },
    {
        featureId: 12,
        reportDefinitionId: 112,
        reportUniqueId: null,
        name: 'Negative Taxes',
        description: 'Employees with Negative Taxes',
        isCustomReport: false,
        clientId: 0,
        createdUserId: 0,
    },
    {
        featureId: 13,
        reportDefinitionId: 113,
        reportUniqueId: null,
        name: 'Deduction Limit Violations',
        description: 'Employees with Deduction Limit Violations',
        isCustomReport: false,
        clientId: 0,
        createdUserId: 0,
    },
    {
        featureId: 14,
        reportDefinitionId: 114,
        reportUniqueId: null,
        name: 'Earning Limit Violations',
        description: 'Employees with Earning Limit Violations',
        isCustomReport: false,
        clientId: 0,
        createdUserId: 0,
    },
    {
        featureId: 15,
        reportDefinitionId: 115,
        reportUniqueId: null,
        name: 'Paid In Advance Differ From WFM Hours',
        description: 'Paid In Advance Differ From WFM Hours',
        isCustomReport: false,
        clientId: 0,
        createdUserId: 0,
    },
    {
        featureId: 16,
        reportDefinitionId: 116,
        reportUniqueId: null,
        name: 'Missing HSA Account Numbers',
        description: null,
        isCustomReport: true,
        clientId: 1086,
        createdUserId: 1001,
    },
    {
        featureId: 17,
        reportDefinitionId: 117,
        reportUniqueId: null,
        name: 'Missing Docket Audit',
        description: null,
        isCustomReport: true,
        clientId: 1086,
        createdUserId: 1001,
    },
    {
        featureId: 18,
        reportDefinitionId: 118,
        reportUniqueId: null,
        name: 'Multi-State Threshold Taxation Status Copy Fixed',
        description:
            'Threshold Amount, Balance and Remainder data for managing multi-state threshold taxation',
        isCustomReport: true,
        clientId: 1086,
        createdUserId: 1001,
    },
    {
        featureId: 19,
        reportDefinitionId: 119,
        reportUniqueId: null,
        name: 'Active Employees Not Paid',
        description: 'Active Employees Not Paid',
        isCustomReport: false,
        clientId: 0,
        createdUserId: 0,
    },
    {
        featureId: 20,
        reportDefinitionId: null,
        reportUniqueId: null,
        name: 'CPF Employee Not calculated',
        description: 'Employee CPF is Not configured In Tax Definition',
        isCustomReport: false,
        clientId: 0,
        createdUserId: 0,
    },
    {
        featureId: 21,
        reportDefinitionId: 121,
        reportUniqueId: null,
        name: 'Direct Deposit Account Changes',
        description:
            'Employee direct deposit account changes since the last normal payroll processing',
        isCustomReport: false,
        clientId: 0,
        createdUserId: 0,
    },
    {
        featureId: 22,
        reportDefinitionId: 122,
        reportUniqueId: null,
        name: 'CPF Employer Not Calculated',
        description: 'Employee CPF is Not Configured in Tax Definition ',
        isCustomReport: false,
        clientId: 0,
        createdUserId: 0,
    },
    {
        featureId: 23,
        reportDefinitionId: 123,
        reportUniqueId: null,
        name: 'CPF Maximum Limit Reached',
        description: 'Calculated CPF Amount Maximum Limit Reached',
        isCustomReport: false,
        clientId: 0,
        createdUserId: 0,
    },
];
