import { AuditDetailsColumn } from '@models/reports';

//Employees earning less than minimum statutory salary
export const mockAuditDetailsColumns_earning: AuditDetailsColumn[] = [
    {
        AccessAuthorizationId: null,
        OriginalDataTypeId: 0,
        AggregateFunction: null,
        AttributeName: 'PRPayRunResult.EmployeeNumber',
        AuthKey: null,
        CategoryLongName: null,
        CategoryShortName: null,
        ClientId: 0,
        ColumnNumber: 1,
        DataTypeId: 0,
        Expression: null,
        GroupBySequence: null,
        IsEmployeeProperty: null,
        IsTransient: null,
        LastModifiedUserId: null,
        LongName: 'Employee number at the time payroll was processed',
        OrderByDirection: null,
        OrderBySequence: null,
        QuerySubjectDataCategoryId: -2147482076,
        QuerySubjectDataId: -2147483621,
        QuerySubjectId: null,
        ReferenceData: null,
        ReportDefinitionId: -2147483462,
        ReportSubjectDataId: -2147483648,
        SchemaName: 'UFJQYXlSdW5SZXN1bHQuRW1wbG95ZWVOdW1iZXI=',
        ShortName: 'Employee Number',
        CustomTotalAccessAuthorizationId: null,
        CustomTotalDataTypeId: null,
        CustomTotalExpression: null,
        IsCustomName: false,
        EnableUtils: true,
        ClientEntityId: null,
        EntityState: 0,
        LastModifiedTimestamp: null,
        LocalizedName: 'Employee Number',
        LocalizedDescription:
            'Employee number at the time payroll was processed',
        PrimaryKeyId: null,
        OriginalValues: null,
        ExtendedProperties: [],
    },
    {
        AccessAuthorizationId: null,
        OriginalDataTypeId: 0,
        AggregateFunction: null,
        AttributeName: 'PRPayRunResult.EmployeeName',
        AuthKey: null,
        CategoryLongName: null,
        CategoryShortName: null,
        ClientId: 0,
        ColumnNumber: 2,
        DataTypeId: 0,
        Expression: null,
        GroupBySequence: null,
        IsEmployeeProperty: null,
        IsTransient: null,
        LastModifiedUserId: null,
        LongName: 'Employee name at the time payroll was processed',
        OrderByDirection: null,
        OrderBySequence: null,
        QuerySubjectDataCategoryId: -2147482076,
        QuerySubjectDataId: -2147483622,
        QuerySubjectId: null,
        ReferenceData: null,
        ReportDefinitionId: -2147483462,
        ReportSubjectDataId: -2147483647,
        SchemaName: 'UFJQYXlSdW5SZXN1bHQuRW1wbG95ZWVOYW1l',
        ShortName: 'Employee Name',
        CustomTotalAccessAuthorizationId: null,
        CustomTotalDataTypeId: null,
        CustomTotalExpression: null,
        IsCustomName: false,
        EnableUtils: true,
        ClientEntityId: null,
        EntityState: 0,
        LastModifiedTimestamp: null,
        LocalizedName: 'Employee Name',
        LocalizedDescription: 'Employee name at the time payroll was processed',
        PrimaryKeyId: null,
        OriginalValues: null,
        ExtendedProperties: [],
    },
    {
        AccessAuthorizationId: -2,
        OriginalDataTypeId: 3,
        AggregateFunction: null,
        AttributeName: 'MonthlySalaryAsofPayDate',
        AuthKey: 'REPORTING_NONE_KEY',
        CategoryLongName: null,
        CategoryShortName: null,
        ClientId: 0,
        ColumnNumber: 3,
        DataTypeId: 4,
        Expression: 'UFJQYXlSdW5SZXN1bHQuQmFzZVNhbGFyeS8xMg==',
        GroupBySequence: null,
        IsEmployeeProperty: null,
        IsTransient: null,
        LastModifiedUserId: null,
        LongName:
            'Monthly Salary of employee as of pay run pay date based on pay run Base Salary',
        OrderByDirection: null,
        OrderBySequence: null,
        QuerySubjectDataCategoryId: null,
        QuerySubjectDataId: null,
        QuerySubjectId: null,
        ReferenceData: null,
        ReportDefinitionId: -2147483462,
        ReportSubjectDataId: -2147483646,
        SchemaName: null,
        ShortName: 'Monthly Salary As of Pay Date',
        CustomTotalAccessAuthorizationId: null,
        CustomTotalDataTypeId: null,
        CustomTotalExpression: null,
        IsCustomName: false,
        EnableUtils: true,
        ClientEntityId: null,
        EntityState: 0,
        LastModifiedTimestamp: null,
        LocalizedName: 'Monthly Salary As of Pay Date',
        LocalizedDescription:
            'Monthly Salary of employee as of pay run pay date based on pay run Base Salary',
        PrimaryKeyId: null,
        OriginalValues: null,
        ExtendedProperties: [],
    },
    {
        AccessAuthorizationId: null,
        OriginalDataTypeId: 6,
        AggregateFunction: null,
        AttributeName: 'PRPayRun.PayDate',
        AuthKey: null,
        CategoryLongName: null,
        CategoryShortName: null,
        ClientId: 0,
        ColumnNumber: 4,
        DataTypeId: 6,
        Expression: null,
        GroupBySequence: null,
        IsEmployeeProperty: null,
        IsTransient: null,
        LastModifiedUserId: null,
        LongName: 'Date upon which an employee is paid',
        OrderByDirection: null,
        OrderBySequence: null,
        QuerySubjectDataCategoryId: -2147482122,
        QuerySubjectDataId: -2147483450,
        QuerySubjectId: null,
        ReferenceData: null,
        ReportDefinitionId: -2147483462,
        ReportSubjectDataId: -2147483645,
        SchemaName: 'UFJQYXlSdW4uUGF5RGF0ZQ==',
        ShortName: 'Pay Run Pay Date',
        CustomTotalAccessAuthorizationId: null,
        CustomTotalDataTypeId: null,
        CustomTotalExpression: null,
        IsCustomName: false,
        EnableUtils: true,
        ClientEntityId: null,
        EntityState: 0,
        LastModifiedTimestamp: null,
        LocalizedName: 'Pay Run Pay Date',
        LocalizedDescription: 'Date upon which an employee is paid',
        PrimaryKeyId: null,
        OriginalValues: null,
        ExtendedProperties: [],
    },
];
