import { AuditDetailsColumn } from '@models/reports';

export const mockAuditDetailsColumns: AuditDetailsColumn[] = [
    {
        AccessAuthorizationId: null,
        OriginalDataTypeId: 0,
        AggregateFunction: null,
        AttributeName: 'ActiveEmployeesNotPaidView.EmployeeNumber',
        AuthKey: null,
        CategoryLongName: null,
        CategoryShortName: null,
        ClientId: 0,
        ColumnNumber: 1,
        DataTypeId: 0,
        Expression: null,
        GroupBySequence: null,
        IsEmployeeProperty: null,
        IsTransient: null,
        LastModifiedUserId: null,
        LongName: 'Number',
        OrderByDirection: null,
        OrderBySequence: null,
        QuerySubjectDataCategoryId: -2147483468,
        QuerySubjectDataId: -2147483643,
        QuerySubjectId: null,
        ReferenceData: null,
        ReportDefinitionId: -2147483460,
        ReportSubjectDataId: -2147483648,
        SchemaName: 'QWN0aXZlRW1wbG95ZWVzTm90UGFpZFZpZXcuRW1wbG95ZWVOdW1iZXI=',
        ShortName: 'Number',
        CustomTotalAccessAuthorizationId: null,
        CustomTotalDataTypeId: null,
        CustomTotalExpression: null,
        IsCustomName: false,
        EnableUtils: true,
        ClientEntityId: null,
        EntityState: 0,
        LastModifiedTimestamp: null,
        LocalizedName: 'Number',
        LocalizedDescription: 'Number',
        PrimaryKeyId: null,
        OriginalValues: null,
        ExtendedProperties: [],
    },
    {
        AccessAuthorizationId: null,
        OriginalDataTypeId: 0,
        AggregateFunction: null,
        AttributeName: 'ActiveEmployeesNotPaidView.EmployeeName',
        AuthKey: null,
        CategoryLongName: null,
        CategoryShortName: null,
        ClientId: 0,
        ColumnNumber: 2,
        DataTypeId: 0,
        Expression: null,
        GroupBySequence: null,
        IsEmployeeProperty: null,
        IsTransient: null,
        LastModifiedUserId: null,
        LongName: 'Display Name',
        OrderByDirection: null,
        OrderBySequence: null,
        QuerySubjectDataCategoryId: -2147483468,
        QuerySubjectDataId: -2147483646,
        QuerySubjectId: null,
        ReferenceData: null,
        ReportDefinitionId: -2147483460,
        ReportSubjectDataId: -2147483647,
        SchemaName: 'QWN0aXZlRW1wbG95ZWVzTm90UGFpZFZpZXcuRW1wbG95ZWVOYW1l',
        ShortName: 'Display Name',
        CustomTotalAccessAuthorizationId: null,
        CustomTotalDataTypeId: null,
        CustomTotalExpression: null,
        IsCustomName: false,
        EnableUtils: true,
        ClientEntityId: null,
        EntityState: 0,
        LastModifiedTimestamp: null,
        LocalizedName: 'Display Name',
        LocalizedDescription: 'Display Name',
        PrimaryKeyId: null,
        OriginalValues: null,
        ExtendedProperties: [],
    },
    {
        AccessAuthorizationId: null,
        OriginalDataTypeId: 2,
        AggregateFunction: null,
        AttributeName: 'ActiveEmployeesNotPaidView.EmploymentGroup',
        AuthKey: null,
        CategoryLongName: null,
        CategoryShortName: null,
        ClientId: 0,
        ColumnNumber: 3,
        DataTypeId: 0,
        Expression: null,
        GroupBySequence: null,
        IsEmployeeProperty: null,
        IsTransient: null,
        LastModifiedUserId: null,
        LongName: 'Status Group',
        OrderByDirection: null,
        OrderBySequence: null,
        QuerySubjectDataCategoryId: -2147483468,
        QuerySubjectDataId: -2147483645,
        QuerySubjectId: null,
        ReferenceData: null,
        ReportDefinitionId: -2147483460,
        ReportSubjectDataId: -2147483646,
        SchemaName: 'QWN0aXZlRW1wbG95ZWVzTm90UGFpZFZpZXcuRW1wbG95bWVudEdyb3Vw',
        ShortName: 'Status Group',
        CustomTotalAccessAuthorizationId: null,
        CustomTotalDataTypeId: null,
        CustomTotalExpression: null,
        IsCustomName: false,
        EnableUtils: true,
        ClientEntityId: null,
        EntityState: 0,
        LastModifiedTimestamp: null,
        LocalizedName: 'Status Group',
        LocalizedDescription: 'Status Group',
        PrimaryKeyId: null,
        OriginalValues: null,
        ExtendedProperties: [],
    },
    {
        AccessAuthorizationId: null,
        OriginalDataTypeId: 0,
        AggregateFunction: null,
        AttributeName: 'ActiveEmployeesNotPaidView.EmployeeDepartmentName',
        AuthKey: null,
        CategoryLongName: null,
        CategoryShortName: null,
        ClientId: 0,
        ColumnNumber: 4,
        DataTypeId: 0,
        Expression: null,
        GroupBySequence: null,
        IsEmployeeProperty: null,
        IsTransient: null,
        LastModifiedUserId: null,
        LongName: 'Department',
        OrderByDirection: null,
        OrderBySequence: null,
        QuerySubjectDataCategoryId: -2147483468,
        QuerySubjectDataId: -2147483647,
        QuerySubjectId: null,
        ReferenceData: null,
        ReportDefinitionId: -2147483460,
        ReportSubjectDataId: -2147483645,
        SchemaName:
            'QWN0aXZlRW1wbG95ZWVzTm90UGFpZFZpZXcuRW1wbG95ZWVEZXBhcnRtZW50TmFtZQ==',
        ShortName: 'Department',
        CustomTotalAccessAuthorizationId: null,
        CustomTotalDataTypeId: null,
        CustomTotalExpression: null,
        IsCustomName: false,
        EnableUtils: true,
        ClientEntityId: null,
        EntityState: 0,
        LastModifiedTimestamp: null,
        LocalizedName: 'Department',
        LocalizedDescription: 'Department',
        PrimaryKeyId: null,
        OriginalValues: null,
        ExtendedProperties: [],
    },
    {
        AccessAuthorizationId: null,
        OriginalDataTypeId: 0,
        AggregateFunction: null,
        AttributeName: 'ActiveEmployeesNotPaidView.PayTypeGroupName',
        AuthKey: null,
        CategoryLongName: null,
        CategoryShortName: null,
        ClientId: 0,
        ColumnNumber: 5,
        DataTypeId: 0,
        Expression: null,
        GroupBySequence: null,
        IsEmployeeProperty: null,
        IsTransient: null,
        LastModifiedUserId: null,
        LongName: 'Pay Type Group',
        OrderByDirection: null,
        OrderBySequence: null,
        QuerySubjectDataCategoryId: -2147483468,
        QuerySubjectDataId: -2147483642,
        QuerySubjectId: null,
        ReferenceData: null,
        ReportDefinitionId: -2147483460,
        ReportSubjectDataId: -2147483644,
        SchemaName:
            'QWN0aXZlRW1wbG95ZWVzTm90UGFpZFZpZXcuUGF5VHlwZUdyb3VwTmFtZQ==',
        ShortName: 'Pay Type Group',
        CustomTotalAccessAuthorizationId: null,
        CustomTotalDataTypeId: null,
        CustomTotalExpression: null,
        IsCustomName: false,
        EnableUtils: true,
        ClientEntityId: null,
        EntityState: 0,
        LastModifiedTimestamp: null,
        LocalizedName: 'Pay Type Group',
        LocalizedDescription: 'Pay Type Group',
        PrimaryKeyId: null,
        OriginalValues: null,
        ExtendedProperties: [],
    },
    {
        AccessAuthorizationId: null,
        OriginalDataTypeId: 0,
        AggregateFunction: null,
        AttributeName: 'ActiveEmployeesNotPaidView.Location',
        AuthKey: null,
        CategoryLongName: null,
        CategoryShortName: null,
        ClientId: 0,
        ColumnNumber: 6,
        DataTypeId: 0,
        Expression: null,
        GroupBySequence: null,
        IsEmployeeProperty: null,
        IsTransient: null,
        LastModifiedUserId: null,
        LongName: 'Location',
        OrderByDirection: null,
        OrderBySequence: null,
        QuerySubjectDataCategoryId: -2147483467,
        QuerySubjectDataId: -2147483644,
        QuerySubjectId: null,
        ReferenceData: null,
        ReportDefinitionId: -2147483460,
        ReportSubjectDataId: -2147483643,
        SchemaName: 'QWN0aXZlRW1wbG95ZWVzTm90UGFpZFZpZXcuTG9jYXRpb24=',
        ShortName: 'Location',
        CustomTotalAccessAuthorizationId: null,
        CustomTotalDataTypeId: null,
        CustomTotalExpression: null,
        IsCustomName: false,
        EnableUtils: true,
        ClientEntityId: null,
        EntityState: 0,
        LastModifiedTimestamp: null,
        LocalizedName: 'Location',
        LocalizedDescription: 'Location',
        PrimaryKeyId: null,
        OriginalValues: null,
        ExtendedProperties: [],
    },
];
