import { AuditDetailsData } from '@models/reports';

export const mockAuditDetailsData: AuditDetailsData[] = [
    {
        RowId: 0,
        Fields: [
            {
                ApplyHighlight: false,
                DataType: 0,
                HighlightColor: null,
                IsPrivacyField: false,
                LongName: 'Number',
                Sequence: 1,
                ShortName: 'Number',
                TypeCode: 18,
                Value: '10001',
                FormattingStyle: null,
                IsValuePreFormatted: false,
                IsCustomTotalValuePreFormatted: false,
                SortValue: null,
                ReportSubjectDataId: -2147483648,
                CustomTotalExpression: null,
                IsGroupBy: false,
                HasColumnTotal: false,
                IsKey: false,
                FlaggedAsDuplicateReason: false,
                EnableUtils: true,
                ClientEntityId: null,
                EntityState: 0,
                LastModifiedTimestamp: null,
                LocalizedName: 'Number',
                LocalizedDescription: 'Number',
                PrimaryKeyId: null,
                OriginalValues: null,
                ExtendedProperties: [],
            },
            {
                ApplyHighlight: false,
                DataType: 0,
                HighlightColor: null,
                IsPrivacyField: false,
                LongName: 'Display Name',
                Sequence: 2,
                ShortName: 'Display Name',
                TypeCode: 18,
                Value: 'Lname Fname',
                FormattingStyle: null,
                IsValuePreFormatted: false,
                IsCustomTotalValuePreFormatted: false,
                SortValue: null,
                ReportSubjectDataId: -2147483647,
                CustomTotalExpression: null,
                IsGroupBy: false,
                HasColumnTotal: false,
                IsKey: false,
                FlaggedAsDuplicateReason: false,
                EnableUtils: true,
                ClientEntityId: null,
                EntityState: 0,
                LastModifiedTimestamp: null,
                LocalizedName: 'Display Name',
                LocalizedDescription: 'Display Name',
                PrimaryKeyId: null,
                OriginalValues: null,
                ExtendedProperties: [],
            },
            {
                ApplyHighlight: false,
                DataType: 0,
                HighlightColor: null,
                IsPrivacyField: false,
                LongName: 'Status Group',
                Sequence: 3,
                ShortName: 'Status Group',
                TypeCode: 18,
                Value: 'Active',
                FormattingStyle: null,
                IsValuePreFormatted: false,
                IsCustomTotalValuePreFormatted: false,
                SortValue: null,
                ReportSubjectDataId: -2147483646,
                CustomTotalExpression: null,
                IsGroupBy: false,
                HasColumnTotal: false,
                IsKey: false,
                FlaggedAsDuplicateReason: false,
                EnableUtils: true,
                ClientEntityId: null,
                EntityState: 0,
                LastModifiedTimestamp: null,
                LocalizedName: 'Status Group',
                LocalizedDescription: 'Status Group',
                PrimaryKeyId: null,
                OriginalValues: null,
                ExtendedProperties: [],
            },
            {
                ApplyHighlight: false,
                DataType: 0,
                HighlightColor: null,
                IsPrivacyField: false,
                LongName: 'Department',
                Sequence: 4,
                ShortName: 'Department',
                TypeCode: 18,
                Value: 'Shoe Management',
                FormattingStyle: null,
                IsValuePreFormatted: false,
                IsCustomTotalValuePreFormatted: false,
                SortValue: null,
                ReportSubjectDataId: -2147483645,
                CustomTotalExpression: null,
                IsGroupBy: false,
                HasColumnTotal: false,
                IsKey: false,
                FlaggedAsDuplicateReason: false,
                EnableUtils: true,
                ClientEntityId: null,
                EntityState: 0,
                LastModifiedTimestamp: null,
                LocalizedName: 'Department',
                LocalizedDescription: 'Department',
                PrimaryKeyId: null,
                OriginalValues: null,
                ExtendedProperties: [],
            },
            {
                ApplyHighlight: false,
                DataType: 0,
                HighlightColor: null,
                IsPrivacyField: false,
                LongName: 'Pay Type Group',
                Sequence: 5,
                ShortName: 'Pay Type Group',
                TypeCode: 18,
                Value: 'Salary',
                FormattingStyle: null,
                IsValuePreFormatted: false,
                IsCustomTotalValuePreFormatted: false,
                SortValue: null,
                ReportSubjectDataId: -2147483644,
                CustomTotalExpression: null,
                IsGroupBy: false,
                HasColumnTotal: false,
                IsKey: false,
                FlaggedAsDuplicateReason: false,
                EnableUtils: true,
                ClientEntityId: null,
                EntityState: 0,
                LastModifiedTimestamp: null,
                LocalizedName: 'Pay Type Group',
                LocalizedDescription: 'Pay Type Group',
                PrimaryKeyId: null,
                OriginalValues: null,
                ExtendedProperties: [],
            },
            {
                ApplyHighlight: false,
                DataType: 0,
                HighlightColor: null,
                IsPrivacyField: false,
                LongName: 'Location',
                Sequence: 6,
                ShortName: 'Location',
                TypeCode: 18,
                Value: 'AL Shoe Management',
                FormattingStyle: null,
                IsValuePreFormatted: false,
                IsCustomTotalValuePreFormatted: false,
                SortValue: null,
                ReportSubjectDataId: -2147483643,
                CustomTotalExpression: null,
                IsGroupBy: false,
                HasColumnTotal: false,
                IsKey: false,
                FlaggedAsDuplicateReason: false,
                EnableUtils: true,
                ClientEntityId: null,
                EntityState: 0,
                LastModifiedTimestamp: null,
                LocalizedName: 'Location',
                LocalizedDescription: 'Location',
                PrimaryKeyId: null,
                OriginalValues: null,
                ExtendedProperties: [],
            },
        ],
        RowType: null,
        FlaggedAsDuplicate: false,
        EnableUtils: true,
        ClientEntityId: null,
        EntityState: 0,
        LastModifiedTimestamp: null,
        LocalizedName: '',
        LocalizedDescription: '',
        PrimaryKeyId: 0,
        OriginalValues: null,
        ExtendedProperties: [],
    },
    {
        RowId: 1,
        Fields: [
            {
                ApplyHighlight: false,
                DataType: 0,
                HighlightColor: null,
                IsPrivacyField: false,
                LongName: 'Number',
                Sequence: 1,
                ShortName: 'Number',
                TypeCode: 18,
                Value: '1212121',
                FormattingStyle: null,
                IsValuePreFormatted: false,
                IsCustomTotalValuePreFormatted: false,
                SortValue: null,
                ReportSubjectDataId: -2147483648,
                CustomTotalExpression: null,
                IsGroupBy: false,
                HasColumnTotal: false,
                IsKey: false,
                FlaggedAsDuplicateReason: false,
                EnableUtils: true,
                ClientEntityId: null,
                EntityState: 0,
                LastModifiedTimestamp: null,
                LocalizedName: 'Number',
                LocalizedDescription: 'Number',
                PrimaryKeyId: null,
                OriginalValues: null,
                ExtendedProperties: [],
            },
            {
                ApplyHighlight: false,
                DataType: 0,
                HighlightColor: null,
                IsPrivacyField: false,
                LongName: 'Display Name',
                Sequence: 2,
                ShortName: 'Display Name',
                TypeCode: 18,
                Value: 'Lname2 Fname2',
                FormattingStyle: null,
                IsValuePreFormatted: false,
                IsCustomTotalValuePreFormatted: false,
                SortValue: null,
                ReportSubjectDataId: -2147483647,
                CustomTotalExpression: null,
                IsGroupBy: false,
                HasColumnTotal: false,
                IsKey: false,
                FlaggedAsDuplicateReason: false,
                EnableUtils: true,
                ClientEntityId: null,
                EntityState: 0,
                LastModifiedTimestamp: null,
                LocalizedName: 'Display Name',
                LocalizedDescription: 'Display Name',
                PrimaryKeyId: null,
                OriginalValues: null,
                ExtendedProperties: [],
            },
            {
                ApplyHighlight: false,
                DataType: 0,
                HighlightColor: null,
                IsPrivacyField: false,
                LongName: 'Status Group',
                Sequence: 3,
                ShortName: 'Status Group',
                TypeCode: 18,
                Value: 'Inactive',
                FormattingStyle: null,
                IsValuePreFormatted: false,
                IsCustomTotalValuePreFormatted: false,
                SortValue: null,
                ReportSubjectDataId: -2147483646,
                CustomTotalExpression: null,
                IsGroupBy: false,
                HasColumnTotal: false,
                IsKey: false,
                FlaggedAsDuplicateReason: false,
                EnableUtils: true,
                ClientEntityId: null,
                EntityState: 0,
                LastModifiedTimestamp: null,
                LocalizedName: 'Status Group',
                LocalizedDescription: 'Status Group',
                PrimaryKeyId: null,
                OriginalValues: null,
                ExtendedProperties: [],
            },
            {
                ApplyHighlight: false,
                DataType: 0,
                HighlightColor: null,
                IsPrivacyField: false,
                LongName: 'Department',
                Sequence: 4,
                ShortName: 'Department',
                TypeCode: 18,
                Value: 'Shoe Management',
                FormattingStyle: null,
                IsValuePreFormatted: false,
                IsCustomTotalValuePreFormatted: false,
                SortValue: null,
                ReportSubjectDataId: -2147483645,
                CustomTotalExpression: null,
                IsGroupBy: false,
                HasColumnTotal: false,
                IsKey: false,
                FlaggedAsDuplicateReason: false,
                EnableUtils: true,
                ClientEntityId: null,
                EntityState: 0,
                LastModifiedTimestamp: null,
                LocalizedName: 'Department',
                LocalizedDescription: 'Department',
                PrimaryKeyId: null,
                OriginalValues: null,
                ExtendedProperties: [],
            },
            {
                ApplyHighlight: false,
                DataType: 0,
                HighlightColor: null,
                IsPrivacyField: false,
                LongName: 'Pay Type Group',
                Sequence: 5,
                ShortName: 'Pay Type Group',
                TypeCode: 18,
                Value: 'Hourly',
                FormattingStyle: null,
                IsValuePreFormatted: false,
                IsCustomTotalValuePreFormatted: false,
                SortValue: null,
                ReportSubjectDataId: -2147483644,
                CustomTotalExpression: null,
                IsGroupBy: false,
                HasColumnTotal: false,
                IsKey: false,
                FlaggedAsDuplicateReason: false,
                EnableUtils: true,
                ClientEntityId: null,
                EntityState: 0,
                LastModifiedTimestamp: null,
                LocalizedName: 'Pay Type Group',
                LocalizedDescription: 'Pay Type Group',
                PrimaryKeyId: null,
                OriginalValues: null,
                ExtendedProperties: [],
            },
            {
                ApplyHighlight: false,
                DataType: 0,
                HighlightColor: null,
                IsPrivacyField: false,
                LongName: 'Location',
                Sequence: 6,
                ShortName: 'Location',
                TypeCode: 18,
                Value: 'AL Shoe Management',
                FormattingStyle: null,
                IsValuePreFormatted: false,
                IsCustomTotalValuePreFormatted: false,
                SortValue: null,
                ReportSubjectDataId: -2147483643,
                CustomTotalExpression: null,
                IsGroupBy: false,
                HasColumnTotal: false,
                IsKey: false,
                FlaggedAsDuplicateReason: false,
                EnableUtils: true,
                ClientEntityId: null,
                EntityState: 0,
                LastModifiedTimestamp: null,
                LocalizedName: 'Location',
                LocalizedDescription: 'Location',
                PrimaryKeyId: null,
                OriginalValues: null,
                ExtendedProperties: [],
            },
        ],
        RowType: null,
        FlaggedAsDuplicate: false,
        EnableUtils: true,
        ClientEntityId: null,
        EntityState: 0,
        LastModifiedTimestamp: null,
        LocalizedName: '',
        LocalizedDescription: '',
        PrimaryKeyId: 1,
        OriginalValues: null,
        ExtendedProperties: [],
    },
];
