export const CheckTemplateConstants = {
    CODE_NAME_NORMAL: 'NORMAL',
    CODE_NAME_NORMAL_ADDITIONAL: 'REGULAR_ADDITIONAL',
    CODE_NAME_MANUAL: 'MANUAL',
    CODE_NAME_ONSITE: 'ONSITE',
    CODE_NAME_ADDITIONAL: 'ADDITIONAL',
    CODE_NAME_ADJUSTMENT: 'ADJUSTMENT',
    CODE_NAME_AUTO_VOID: 'AUTO_VOID',
    CODE_NAME_THIRD_PARTY_SICK_PAY_ADJUSTMENT:
        'THIRD_PARTY_SICK_PAY_ADJUSTMENT',
    CODE_NAME_ON_DEMAND: 'ONDEMAND',
    CODE_NAME_ON_DEMAND_TRUEUP: 'ONDEMAND_TRUEUP',
    CODE_NAME_OFF_CYCLE: 'OFF_CYCLE',
    CODE_NAME_PENSIONER: 'PENSIONER',
    CODE_NAME_DECEASED: 'DECEASED',
    CODE_NAME_ADVANCE_PAY: 'ADVANCE_PAY',
    CODE_NAME_RETRO_PAY: 'RETRO_PAY',
};
export const CheckTemplateSpecialPayConstants = {
    ADVANCE_PAY_TYPE: 1,
    RETRO_PAY_TYPE: 2,
};
