export const CheckTypeConstants = {
    CODE_NAME_NORMAL: 'NORMAL',
    CODE_NAME_MANUAL: 'MANUAL',
    CODE_NAME_ONSITE: 'ONSITE',
    CODE_NAME_ADDITIONAL: 'ADDITIONAL',
    CODE_NAME_ADJUSTMENT: 'ADJUSTMENT',
    CODE_NAME_AUTO_VOID: 'AUTO_VOID',
    CODE_NAME_REGULAR_ADDITIONAL: 'REGULAR_ADDITIONAL',
    CODE_NAME_THIRD_PARTY_SICK_PAY_ADJUSTMENT:
        'THIRD_PARTY_SICK_PAY_ADJUSTMENT',
    CODE_NAME_ONDEMAND: 'ONDEMAND',
    CODE_NAME_ONDEMAND_TRUEUP: 'ONDEMAND_TRUEUP',
    CODE_NAME_ONDEMAND_VOID: 'ONDEMAND_VOID',
};
