export const DataEntryConstants = {
    Filter_EmployeeDisplayName_FIELD: 'DisplayName',
    Filter_EmployeeNumber_FIELD: 'EmployeeNumber',
    Filter_SSNSIN_FIELD: 'SSNSIN',
    Filter_Job_FIELD: 'Job',
    Filter_Position_FIELD: 'Position',
    Filter_PayGroup_FIELD: 'PayGroup',
    Filter_WorkLocation_FIELD: 'WorkLocation',
    Filter_PREarningType_FIELD: 'PREarningTypeId',
    Filter_PRDeductionTaxType_FIELD: 'PRDeductionTaxTypeId',
    Filter_CheckTeplate_FIELD: 'CheckTeplate',
    Filter_PRPayrollEditSet_FIELD: 'PRPayRunLoadedEditSetId',
    Filter_PRPayRun_FIELD: 'PRPayRunId',
    Filter_PRPayRunOfUSA_FIELD: 'PRPayRunIdOfUSA',
    Filter_PPN_FIELD: 'PPN',
    Filter_Replace_FIELD: 'Replace',
    Filter_SavedBy_FIELD: 'SavedBy',
    Filter_Source_FIELD: 'Source',
    Filter_Project_FIELD: 'ProjectId',
    Filter_Docket_FIELD: 'DocketId',
    Filter_PRPayrollTaxType_FIELD: 'PRPayrollTaxTypeId',
    Filter_DataEntryImport_FIELD: 'PRPayEntryDataBatchImportSetId',
    Filter_CheckEntryImport_FIELD: 'PRPayEntryCheckBatchImportSetId',
    Filter_AdjustmentEntryImport_FIELD: 'PRPayEntryAdjustmentBatchImportSetId',
    Filter_CheckType_FIELD: 'CheckType',
    Filter_DisbursementMethod_FIELD: 'DisbursementMethod',
    Filter_CommitStatus_FIELD: 'CommitStatus',
    Filter_CheckNumber_FIELD: 'CheckNumber',
    Filter_CheckDate_FIELD: 'CheckDate',
    Filter_RetroOnly_FIELD: 'RetroOnly',
    Filter_PayType_FIELD: 'PayType',
    Filter_PREarning_FIELD: 'PREarning',
    Filter_PRDeduction_FIELD: 'PRDeduction',
    Filter_BusinessDate_FIELD: 'BusinessDate',
    Filter_WeekNumber_FIELD: 'WeekNumber',
    Filter_AdjustmentType_FIELD: 'AdjustmentType',
    Filter_EIReferenceCode_FIELD: 'EIReferenceCode',
    Filter_ThirdPartySickPayProvider_FIELD: 'ThirdPartySickPayProvider',
    Filter_DistributionCode_FIELD: 'DistributionCode',
    Filter_ROE_WorkLocation_FIELD: 'OrgUnit',
    Filter_PayClass_FIELD: 'PayClass',
    Filter_TaxabilityType_FIELD: 'TaxabilityType',
    Filter_TaxCompliance_FIELD: 'TaxCompliance',
    Filter_PayrollTaxType_FIELD: 'PayrollTaxType',
    Filter_PayrollTax_FIELD: 'PayrollTax',
    Filter_LegalEntityPRM_FIELD: 'LegalEntity',
    Filter_EarningHours_FIELD: 'EarningHours',
    Filter_EarningAmount_FIELD: 'EarningAmount',
    Filter_DeductionAmount_FIELD: 'DeductionAmount',
    Filter_TaxAmount_FIELD: 'TaxAmount',
    Filter_LaborMetrics_FIELD: 'LaborMetrics',
    Filter_Department_FIELD: 'Department',
    Filter_ArchivedReportReportName_FIELD: 'ReportName',
    Filter_ArchivedReportIncludeVoidedPayRuns_FIELD: 'IncludeVoidedPayRuns',
    Filter_ArchivedReportDeliveryPackage_FIELD: 'SourceDeliveryPackage',
    Filter_SequenceNumber_FIELD: 'SequenceNumber',
    Filter_StopPaymentPayRun_FIELD: 'StopPaymentPayRun',
    Filter_StopPaymentState_FIELD: 'StopPaymentState',
    Filter_StopPaymentStoppedBy_FIELD: 'StoppedBy',
    Filter_Code_FIELD: 'Code',
    Filter_CompensationCycle_FIELD: 'CompensationCycle',
    Filter_PayComponent_FIELD: 'PayComponent',
    Filter_PayRunResult: 'PayRunResult',
    Filter_PayRunResultSummary: 'PayRunResultSummary',
    Filter_EmploymentStatus: 'EmploymentStatus',
    Filter_OnDemandCommitState_FIELD: 'OnDemandCommitState',
    Filter_OnDemandRequestedDateUTC_FIELD: 'OnDemandRequestedDateUTC',
    Filter_OnDemandCommittedDateUTC_FIELD: 'OnDemandCommittedDateUTC',
    Filter_Location_FIELD: 'Location',
    Filter_Unpublished_FIELD: 'Unpublished',
    Filter_Published_FIELD: 'Published',
    Filter_RecordsWithErrorOrWarnings_FIELD: 'RecordsWithErrorOrWarnings',
    Filter_EIWOFileName_FIELD: 'EIWOFileName',
    Filter_FEIN_FIELD: 'FEIN',
    Filter_DocType_FIELD: 'DocType',
    Filter_EmployeSSN_FIELD: 'EmployeeSSN',
    Filter_EmployeeLastName_FIELD: 'EmployeeLastName',
    Filter_CaseNumber_FIELD: 'CaseNumber',
    Filter_PayrollImportQuickEntriesPayRun_FIELD:
        'PayrollImportQuickEntriesPayRun',

    StaleEntries: 'lblEntriesAreStale',
    NoAccessToEarningDeductionCode: 'lblNoAccessToEarningOrDeductionCode',
    NoVisibilityToSelf: 'lblNoVisibilityToself',
    NoBusinessOwnerGroupSaved: 'lblNoBusinessOwnerGroupSaved2',
    EntryAlreadyPublished: 'lblEntryPublished',
    FeatureIsNotEnabled: 'lblEditFeatureNotEnabled',
    SameUserCantApproveRejectOrSave: 'lblSameUserCantApproveRejectOrSave',
    NoAccessToGroup: 'lblNoAccessToGroup',
    Save_Failed_Server_Error: 'msgDataEntrySavingFailed',
    Save_Failed_Saved_Partially: 'msgDataEntrySavingPartiallySaved',
    Save_Failed_Saved_Successfully: 'msgDataEntrySaveSuccessfully',
    GenerateROE_Failed_Server_Error: 'msgGenerateROEFailed',
    GenerateROE_Failed_Saved_Partially: 'msgGenerateROEPartiallyFinished',
    GenerateROE_Saved_Successfully: 'msgGenerateROECompletedSuccessfully',
    OnsiteChecksCreateFeature: 'OnSiteChecksCreate',
    OnsiteChecksCreateNewFeature: 'OnSiteChecksCreateNew',
    OnSiteChecksDeleteFeature: 'OnSiteChecksDelete',
    OnSiteChecksDeleteNewFeature: 'OnSiteChecksDeleteNew',
    OnSiteChecksPrintFeature: 'OnSiteChecksPrint',
    OnSiteChecksPrintNewFeature: 'OnSiteChecksPrintNew',
    P45PrintFeature: 'P45Print',
    OverrideInProcessChecks: 'OverrideInProcessChecks',
    OverrideInProcessChecksNew: 'OverrideInProcessChecksNew',
    PayollCardIssueFeature: 'PayollCardIssue',
    PayollCardIssueNewFeature: 'PayollCardIssueNew',
    PayCardInstantIssueFeature: 'WalletPayCard',
    OnDemandSummaryFeature: 'PayrollOnDemandSummary',
    PayrollCardIssueAuthorization: 'HRMS_ISSUE_PAYCARD',
    PayrollCardEmployeeBanking:
        'EmployeeProfile.Payroll.EmployeeBanking.PayrollCard',
    AllowPayCardClientProperty: 'AllowPayCard',
    PayrollCheckAccess: 'PAYROLL_CHECK_ACCESS',
    TimeData_OrgUnitId_SearchParameter: 'OrgUnitId',
    TimeData_PayRunId_SearchParameter: 'PayRunId',
    TimeData_EmployeeId_SearchParameter: 'EmployeeId',
    TimeData_PayGroupId_SearchParameter: 'PayGroupId',
    TimeData_PayGroupCalendarId_SearchParameter: 'PayGroupCalendarId',
    TimeData_OffCyclePayRunId_SearchParameter: 'OffCyclePayRunId',
    TimeData_SelectedSource_SearchParameter: 'SelectedSource',
    BusinessDate_FIELD: 'BusinessDate',
    BusinessOwnerGroup_FIELD: 'GroupsId',
    UseLaborSplit_FIELD: 'UseLaborSplit',
    LaborMetricses_FIELD: 'LaborMetricses',
    DebitArrears_FIELD: 'DebitArrears',
    ApplyROEMapping_FIELD: 'ApplyROEMapping',
    EffectivePeriodStart_FIELD: 'EffectivePeriodStart',
    EffectivePeriodEnd_FIELD: 'EffectivePeriodEnd',
    PRWageAttachmentOrderedAmountTypeId_FIELD:
        'PRWageAttachmentOrderedAmountTypeId',
    PRWageAttachmentOrderedAmountTypeId_DISPLAY_FIELD: 'OrderedAmountTypeName',
    OrderedPercent_FIELD: 'OrderedPercent',
    LimitAmount_FIELD: 'LimitAmount',
    DisposableEarningAmount_FIELD: 'DisposableEarningAmount',
    PayPeriodsForTax_FIELD: 'PayPeriodsForTax',
    EntityState_FIELD: 'EntityState',
    EntityValidationState_Field: 'EntityValidationState',
    EmployeeName_FIELD: 'EmployeeId',
    EmployeeName_DISPLAY_FIELD: 'EmployeeDisplayName',
    EmployeeCard_FIELD: 'EmployeeCard',
    EmployeeNumber_FIELD: 'EmployeeIdForNumber',
    EmployeeNumber_DISPLAY_FIELD: 'EmployeeNumber',
    PRPayRun_FIELD: 'PRPayRunId',
    PayRun_FIELD: 'EmployeePayRunId',
    PayRun_DISPLAY_FIELD: 'PayRunDisplayName',
    PayRun_SHORT_NAME: 'ShortName',
    Replace_FIELD: 'IsOverride',
    IsQuarterAmendment_FIELD: 'IsQuarterAmendment',
    IsYearEndAmendment_FIELD: 'IsYearEndAmendment',
    ImportSetName_FIELD: 'ImportSetName',
    Code_FIELD: 'CodeId',
    TrailingTaxationPeriodStartDate_FIELD: 'TrailingTaxationPeriodStart',
    TrailingTaxationPeriodEndDate_FIELD: 'TrailingTaxationPeriodEnd',
    Approval_DISPLAY_FIELD: 'PRImportApprovalStatus',
    Published_DISPLAY_FIELD: 'IsPublished',
    PublishDate_DISPLAY_FIELD: 'PublicationDate',
    PublishedBy_DISPLAY_FIELD: 'PersonWhoPublishedUserName',
    ImportSet_DISPLAY_FIELD: 'FilterImportSet',
    ApprovableImportSet_DISPLAY_FIELD: 'ApprovableImportSet',
    PayrollElectionImportSet_DISPLAY_FIELD: 'PayrollElectionImportSet',
    PayRunStatus_DISPLAY_FIELD: 'PayRunStatus',
    UploadFile_DISPLAY_FIELD: 'ImportFileName',
    CreatedDate_DISPLAY_FIELD: 'CreatedDate',
    CreatedBy_DISPLAY_FIELD: 'CreatedByUserName',
    BusinessOwnerGroup_DISPLAY_FIELD: 'GroupsDisplayName',
    Code_DISPLAY_FIELD: 'CodeDisplayName',
    AdjustmentCode_DISPLAY_FIELD: 'QuickEntryName',
    Hours_FIELD: 'Unit',
    Rate_FIELD: 'Rate',
    RateCode_FIELD: 'RateCode',
    PRTaxWageType_FIELD: 'PRTaxWageTypeId',
    PRTaxWageType_DISPLAY_FIELD: 'PRTaxWageTypeDescription',
    Amount_FIELD: 'Amount',
    OrderedAmount_FIELD: 'Amount',
    Position_FIELD: 'DeptJobId',
    Position_DISPLAY_FIELD: 'PositionDepartmentName',
    WorkLocation_FIELD: 'OrgUnitId',
    WorkLocation_DISPLAY_FIELD: 'OrgUnitDisplayName',
    LegalEntity_FIELD: 'LegalEntityId',
    LegalEntityEmployeeInsuranceId_FIELD: 'LegalEntityEmployeeInsuranceId',
    ManualLegalEntityEmployeeInsuranceId_FIELD:
        'ManualLegalEntityEmployeeInsuranceId',
    LegalEntityEmployeeInsuranceFullName:
        'LegalEntityEmployeeInsuranceFullName',
    LegalEntity_DISPLAY_FIELD: 'LegalEntityDisplayName',
    CheckTemplate_FIELD: 'PRPayRunDefId',
    CheckTemplate_DISPLAY_FIELD: 'CheckTemplateName',
    EffectivePeriodStart_DISPLAY_FIELD: 'EffectivePeriodStart',
    EffectivePeriodEnd_DISPLAY_FIELD: 'EffectivePeriodEnd',
    Comment_FIELD: 'Comment',
    Check_Comment_FIELD: 'LongName',
    Project_FIELD: 'ProjectId',
    Project_DISPLAY_FIELD: 'ProjectDisplayName',
    Docket_FIELD: 'DocketId',
    Docket_DISPLAY_FIELD: 'DocketDisplayName',
    IsBalancePayOut_FIELD: 'IsBalancePayOut',
    WCBAccountNumberColumn_FIELD: 'PRWCBAccountId',
    WCBAccountNumberColumn_DISPLAY_FIELD: 'PRWCBAccount',
    WCBCodeColumn_FIELD: 'PRWCBCodeId',
    WCBCodeColumn_DISPLAY_FIELD: 'PRWCBCode',
    QunickEntryPayPeriodNumber_DISPLAY_FIELD:
        'AdjPeriodNumberAndYearExportFormat',
    PayPeriodNumber_FIELD: 'AdjustedPriorPeriodRunId',
    PayPeriodNumber_DISPLAY_FIELD: 'AdjPeriodNumberAndYear',
    AdjPayPeriodNumber_DISPLAY_FIELD: 'AdjPayPeriodNumberSuffixAndDate',
    DoNotDisburseToThirdPartyPayee_FIELD: 'DoNotDisburseToThirdPartyPayee',
    SavedBy_FIELD: 'LastModifiedBy',
    SavedBy_FIELD_ADJUSTMENT: 'LastModifiedByAdjustment',
    SavedBy_FIELD_CHECK: 'LastModifiedByCheck',
    SavedBy_FIELD_QUICKENTRY: 'LastModifiedByQuickEntry',
    SavedBy_FIELD_IMPORTQUICKENTRY: 'LastModifiedByImportQuickEntry',
    SavedAt_FIELD: 'LastModifiedAt',
    SavedAtUTC_FIELD: 'LastModifiedAtUTC',
    CurrentWageBasis_FIELD: 'CurrWageBasis',
    HoursWorked_FIELD: 'HoursWorked',
    TaxableWages_FIELD: 'TaxableWages',
    LimitedWCBAssesableWages_FIELD: 'LimitedWCBAssesableWages',
    TotalWCBAssesableWages_FIELD: 'TotalWCBAssesableWages',
    OtherSpecialWages_FIELD: 'OtherSpecialWages',
    CtsCode_FIELD: 'CTSCode',
    IsSentToPaymentSolutions_FIELD: 'IsSentToPaymentSolutions',
    CheckType_FIELD: 'PRPayRunCheckTypeId',
    CheckType_DISPLAY_FIELD: 'CheckTypeName',
    AdjustmentType_DISPLAY_FIELD: 'AdjustmentTypeName',
    Reason_FIELD: 'ReasonId',
    Reason_DISPLAY_FIELD: 'ReasonName',
    DisbursementMethod_FIELD: 'PROnsiteCheckDisbursementMethodId',
    DisbursementMethod_DISPLAY_FIELD: 'DisbursementMethodName',
    ResidenceState_FIELD: 'ResidenceStateCode',
    PayGroupId_FIELD: 'PayGroupId',
    PayGroupDisplay_FIELD: 'PayGroupDisplayName',
    IsVoidedPayRun_FIELD: 'IsVoided',
    ResPSDCode_FIELD: 'ResPSDCode',
    DistributionCode_FIELD: 'DistributionCode',
    PayEntryAdjustmentBatchImportSetName_FIELD:
        'PayEntryAdjustmentBatchImportSetName',
    StageEntryName_FIELD: 'IsStagedEntry',
    PRThirdPartySickPayProviderId_FIELD: 'ThirdPartySickPayProviderName',
    PRThirdPartySickPayProviderId_DISPLAY_FIELD:
        'ThirdPartySickPayProviderName',
    ThirdPartySickPayTaxExemptionCode_FIELD:
        'ThirdPartySickPayTaxExemptionCode',
    ThirdPartySickPayTaxExemption_DISPLAY_FIELD:
        'ThirdPartySickPayTaxExemptionName',
    CommittedDate_FIELD: 'CommittedDate',
    IsStopPaySuccessful_FIELD: 'IsStopPaySuccessful',
    SavedBy_CHECK_FIELD: 'LastModifiedUserLoginId',
    SavedAt_CHECK_FIELD: 'LastModifiedAt',
    ROEGroup_FIELD: 'MassROEGroup',
    ROERequestDate_FIELD: 'RequestDate',
    ROERequestDateUTC_FIELD: 'RequestDateUTC',
    ROERequestedBy_FIELD: 'RequestedBy',
    ROEIssueReason_FIELD: 'PRROEIssueReasonId',
    ROEIssueReason_DISPLAY_FIELD: 'ROEIssueReason',
    ROEState_FIELD: 'ROEStateId',
    ROEState_DISPLAY_FIELD: 'ROEState',
    ROERequestSource_FIELD: 'ROERequestSource',
    ROELegalEntity_FIELD: 'LegalEntityId',
    ROELegalEntity_DISPLAY_FIELD: 'LegalEntityDisplayName',
    ROEAmendment_FIELD: 'AmmendedROERequestId',
    ROERequestId_FIELD: 'EmployeeROERequestId',
    ROELock_FIELD: 'LockROE',
    LoadPayCardAction_FIELD: 'ActionText',
    PayrollCardNumber_FIELD: 'PayrollCardNumber',
    TotalDisbursedNetPay_FIELD: 'TotalDisbursedNetPay',
    PayrollEditSetName_FIELD: 'PRPayRunLoadedEditSetId',
    PayrollEditSetName_DISPLAY_FIELD: 'PayrollEditSetName',
    ReportName_FIELD: 'ReportNameId',
    AlternateTitle_FIELD: 'ReportAlternateTitle',
    ReportNameDisplay_FIELD: 'ReportName',
    PayDate_FIELD: 'PayDate',
    FileGeneratedOn_FIELD: 'GeneratedOn',
    Language_FIELD: 'Language',
    SourceDeliveryPackage_FIELD: 'SourceDeliveryPackage',
    CompensationCycle_FIELD: 'CompensationCycle',
    PayComponent_FIELD: 'PayComponent',
    Problem_FIELD: 'Problems',
    PRPayEntryAdjustmentBatchId_FIELD: 'PRPayEntryAdjustmentBatchId',
    WorkCertificatePosition_FIELD: 'WorkCertificatePosition',

    //Data Entry Configuration Property Name
    DataEntrySaveBatchSize: 'DataEntrySaveBatchSize',
    CheckEntrySaveBatchSize: 'CheckEntrySaveBatchSize',
    AdjustmentSaveBatchSize: 'AdjustmentSaveBatchSize',
    DataEntryDeleteBatchSize: 'DataEntryDeleteBatchSize',

    AdvancePay_FIELD: 'PRAdvancePayWFMDataTypeId',
    AdvancePay_DISPLAY_FIELD: 'AdvancedPayTypeName',
    Locked_FIELD: 'IsLocked',
    WorkCertificateType_FIELD: 'WorkCertificateTypeId',
    WorkCertificateType_DISPLAY_FIELD: 'WorkCertificateTypeDisplayName',

    CountryHiddenColumns: {
        CAN: [
            'ResidenceStateCode',
            'PROnsiteCheckDisbursementMethodId',
            'CommitStateName',
            'CommittedDate',
        ],
        USA: ['ManualLegalEntityEmployeeInsuranceId'],
    },

    DataEntryEmptyCheckColumns: [
        'PRPayRunLoadedEditSetId',
        'EmployeeId',
        'PRPayRunId',
        'CodeId',
        'PRPayRunDefId',
        'IsBalancePayOut',
        'OrgUnitId',
        'DeptJobId',
        'DoNotDisburseToThirdPartyPayee',
        'DocketId',
        'ProjectId',
        'PRWCBAccountId',
        'PRWCBCodeId',
        'EffectivePeriodStart',
        'EffectivePeriodEnd',
        'AdjustedPriorPeriodRunId',
        'CurrWageBasis',
        'TaxableWages',
        'PRWageAttachmentOrderedAmountTypeId',
        'Amount',
        'Rate',
        'Unit',
    ],

    CheckEntryEmptyCheckColumns: [
        'CodeId',
        'CodeDisplayName',
        'TrailingTaxationPeriodStart',
        'TrailingTaxationPeriodEnd',
        'IsOverride',
        'Unit',
        'Rate',
        'Amount',
        'BusinessDate',
        'DeptJobId',
        'PositionDepartmentName',
        'OrgUnitId',
        'OrgUnitDisplayName',
        'LegalEntityId',
        'LegalEntityEmployeeInsuranceId',
        'UseLaborSplit',
        'LaborMetricses',
        'DebitArrears',
        'ApplyROEMapping',
        'Comment',
        'EffectivePeriodStart',
        'EffectivePeriodEnd',
        'ProjectId',
        'ProjectDisplayName',
        'DocketId',
        'DocketDisplayName',
        'PRWageAttachmentOrderedAmountTypeId',
        'OrderedAmountTypeName',
        'OrderedPercent',
        'LimitAmount',
        'DisposableEarningAmount',
        'PayPeriodsForTax',
        'IsBalancePayOut',
        'PRWCBAccountId',
        'PRWCBAccount',
        'PRWCBCodeId',
        'PRWCBCode',
        'CurrWageBasis',
        'TaxableWages',
        'AdjustedPriorPeriodRunId',
        'AdjPeriodNumberAndYear',
        'DoNotDisburseToThirdPartyPayee',
        'ImportSetName',
    ],

    CheckEntryEmptyCheckColumnsWhenCopy: [
        'CodeId',
        'CodeDisplayName',
        'TrailingTaxationPeriodStart',
        'TrailingTaxationPeriodEnd',
        'IsOverride',
        'Unit',
        'Rate',
        'Amount',
        'BusinessDate',
        'DeptJobId',
        'PositionDepartmentName',
        'LegalEntityEmployeeInsuranceId',
        'UseLaborSplit',
        'LaborMetricses',
        'DebitArrears',
        'ApplyROEMapping',
        'Comment',
        'EffectivePeriodStart',
        'EffectivePeriodEnd',
        'ProjectId',
        'ProjectDisplayName',
        'DocketId',
        'DocketDisplayName',
        'PRWageAttachmentOrderedAmountTypeId',
        'OrderedAmountTypeName',
        'OrderedPercent',
        'LimitAmount',
        'DisposableEarningAmount',
        'PayPeriodsForTax',
        'IsBalancePayOut',
        'PRWCBAccountId',
        'PRWCBAccount',
        'PRWCBCodeId',
        'PRWCBCode',
        'CurrWageBasis',
        'TaxableWages',
        'AdjustedPriorPeriodRunId',
        'AdjPeriodNumberAndYear',
        'DoNotDisburseToThirdPartyPayee',
        'ImportSetName',
    ],

    CheckEmptyCheckColumns: [
        'PRPayEntryAdjustmentBatchImportSetId',
        'EmployeeId',
        'PRPayRunId',
        'PRPayRunCheckTypeId',
        'PRPayRunDefId',
        'PRThirdPartySickPayProviderId',
        'PRThirdPartySickPayTaxExemptionId',
        'PROnsiteCheckDisbursementMethodId',
        'PRAdvancePayWFMDataTypeId',
    ],

    //Check Template
    CHECK_TEMPLATE_TYPE_NORMAL: 'NORMAL',
    CHECK_TEMPLATE_TYPE_OFF_CYCLE: 'OFF_CYCLE',
    CHECK_TEMPLATE_TYPE_MANUAL: 'MANUAL',
    CHECK_TEMPLATE_TYPE_MANUAL_WO_ER_TAX: 'MANUAL_WO_ER_TAX',
    CHECK_TEMPLATE_TYPE_MANUAL_ERetention: 'MANUAL_ERetention',
    CHECK_TEMPLATE_TYPE_MANUAL_Covid19: 'MANUAL_Covid19',

    CodeType: {
        Earning: 1,
        Deduction: 2,
        Tax: 3,
        WageAttachment: 4,
    },

    DataEntryModelType: {
        DataEntry: 1,
        Check: 2,
        CheckEntry: 3,
        Adjustment: 4,
        AdjustmentEntry: 5,
        ROEEntry: 6,
    },

    PRCommitState: {
        NONE: 1,
        FAILED: 2,
        INPROCESS: 3,
        COMMITTED: 4,
        CANCELLED: 5,
        REJECTED: 6,
        REVERSED: 7,
    },

    CHECK_TYPE_NORMAL: 'NORMAL',
    CHECK_TYPE_NORMAL_ADDITIONAL: 'REGULAR_ADDITIONAL',
    CHECK_TYPE_MANUAL: 'MANUAL',
    CHECK_TYPE_ONSITE: 'ONSITE',
    CHECK_TYPE_ADDITIONAL: 'ADDITIONAL',
    CHECK_TYPE_ADJUSTMENT: 'ADJUSTMENT',
    CHECK_TYPE_AUTO_VOID: 'AUTO_VOID',
    CHECK_TYPE_THIRD_PARTY_SICK_PAY_ADJUSTMENT:
        'THIRD_PARTY_SICK_PAY_ADJUSTMENT',
    CHECK_TYPE_ON_DEMAND: 'ONDEMAND',
    CHECK_TYPE_ON_DEMAND_TRUEUP: 'ONDEMAND_TRUEUP',

    ADJUSTMENT_TYPE_NORMAL: 'NORMAL',
    ADJUSTMENT_TYPE_MANUAL: 'MANUAL',
    ADJUSTMENT_TYPE_ADDITIONAL: 'ADDITIONAL',
    ADJUSTMENT_TYPE_ONSITE: 'ONSITE',

    THIRD_PARTY_SICK_TAX_EXEMPTION_NO_EXEMPTION: 'NO_EXEMPTION',
    THIRD_PARTY_SICK_TAX_EXEMPTION_NON_TAXABLE: 'NON_TAXABLE',
    THIRD_PARTY_SICK_TAX_TAXABILITY: 'BSIE037',
    THIRD_PARTY_SICK_TAX_AUTHORITYINSTANCE_FICAEE: 'USA-00000000-003',
    THIRD_PARTY_SICK_TAX_AUTHORITYINSTANCE_FedMWTEE: 'USA-00000000-005',

    EarningCode: {
        USTaxibility: 'EarningCodeUSTaxibility',
    },

    BatchDataType: {
        Normal: 0,
        PriorPeriodAdjustment: 1,
        SeparateCheck: 2,
    },

    PaymentMethod: {
        PAYCARD: 'PAYCARD',
        DFWALLETPAYCARD: 'DFWALLETPAYCARD',
        CHECK: 'CHECK',
    },

    LoadPayCardMode: {
        PAYCARD: 'PAYCARD',
        DFWALLETPAYCARD: 'DFWALLETPAYCARD',
        BATCH_PAYCARD: 'BATCH_PAYCARD',
        BATCH_DFWALLETPAYCARD: 'BATCH_DFWALLETPAYCARD',
    },

    DFWalletCardStatus: {
        NEW: 'NEW',
        ACTIVE: 'ACTIVE',
    },

    CommitState: {
        None: 0,
        FAILED: 2,
        INPROCESS: 1,
        COMMITTED: 3,
    },

    CommitState_NONE: 'NONE',
    CommitState_INPROCESS: 'INPROCESS',
    CommitState_COMMITTED: 'COMMITTED',
    CommitState_FAILED: 'FAILED',

    DefaultSortOrderForCheck: 999999,

    MINIMUM_HOUR: -999999.999,
    MAXIMUM_HOUR: 999999.999,
    MINIMUM_RATE: -99999.999,
    MAXIMUM_RATE: 99999.999,
    MINIMUM_AMOUNT: -9999999999999.99999,
    MAXIMUM_AMOUNT: 9999999999999.99999,

    CommonStoreType: {
        OnDemandCommitStateStore: 'OnDemandCommitStateStore',
        PayrollEmployeeSearchStore: 'PayrollEmployeeSearchStore',
        PayrollSlideoutEmployeeSearchStore:
            'PayrollSlideoutEmployeeSearchStore',
        PayrollEmployeeNumberSearchStore: 'PayrollEmployeeNumberSearchStore',
        PayrollEmployeeSearchStoreForAdjustment:
            'PayrollEmployeeSearchStoreForAdjustment',
        PayrollEmployeeSearchStoreForThirdPartySickPay:
            'PayrollEmployeeSearchStoreForThirdPartySickPay',
        PayrollEmployeeSearchStoreFullDisplayName:
            'PayrollEmployeeSearchStoreFullDisplayName',
        PayrollEmployeeNumberSearchStoreForAdjustment:
            'PayrollEmployeeNumberSearchStoreForAdjustment',
        TerminatedEmployeeSearchStore: 'TerminatedEmployeeSearchStore',
        TerminatedEmployeeNumberSearchStore:
            'TerminatedEmployeeNumberSearchStore',
        ROEEmployeeSearchStore: 'ROEEmployeeSearchStore',
        ROEEmployeeNumberSearchStore: 'ROEEmployeeNumberSearchStore',
        P45EmployeeSearchStore: 'P45EmployeeSearchStore',
        P45EmployeeNumberSearchStore: 'P45EmployeeNumberSearchStore',
        WorkCertificateEmployeeSearchStore:
            'WorkCertificateEmployeeSearchStore',
        WorkCertificateEmployeeNumberSearchStore:
            'WorkCertificateEmployeeNumberSearchStore',
        EmployeeMasterStore: 'EmployeeMasterStore',
        CodeStore: 'CodeStore',
        CodeStoreForFiltering: 'CodeStoreForFiltering',
        LegalEntityDataEntryStore: 'LegalEntityDataEntryStore',
        LegalEntityEmployeeInsuranceStore: 'LegalEntityEmployeeInsuranceStore',
        EIReferenceCodeStore: 'EIReferenceCodeStore',
        PRPayRunDefStore: 'PRPayRunDefStore',
        CheckTypeStore: 'CheckTypeStore',
        DisbursementMethodStore: 'DisbursementMethodStore',
        CommitStateStore: 'CommitStateStore',
        PSDCodeByCodeStore: 'PSDCodeByCodeStore',
        PREarningsStore: 'PREarningsStore',
        PriorPayRunStore: 'PriorPayRunStore',
        WcbAccountStore: 'WcbAccountStore',
        WcbCodeStore: 'WcbCodeStore',
        ProjectStore: 'ProjectStore',
        DocketStore: 'DocketStore',
        QuickEntryStore: 'QuickEntryStore',
        ImportIncomeWithholdingAcknowledgementStore:
            'ImportIncomeWithholdingAcknowledgementStore',
        CheckHeaderStore: 'CheckHeaderStore',
        CheckEntryStore: 'CheckEntryStore',
        PRPayrollReasonStore: 'PRPayrollReasonStore',
        AdjustmentsHeaderStore: 'AdjustmentsHeaderStore',
        AdjustmentsEntryStore: 'AdjustmentsEntryStore',
        CompensationDataStore: 'CompensationDataStore',

        CheckEntryLoadedAdjustmentIdStore: 'CheckEntryLoadedAdjustmentIdStore',
        AdjustmentEntryLoadedAdjustmentIdStore:
            'AdjustmentEntryLoadedAdjustmentIdStore',
        AdjustmentEntryLoader: 'AdjustmentEntryLoader',
        CheckEntryLoader: 'CheckEntryLoader',

        DataEntryValidator: 'DataEntryValidator',
        QuickEntryAuditStore: 'QuickEntryAuditStore',
        CheckEntryAuditStore: 'CheckEntryAuditStore',
        AdjustmentEntryAuditStore: 'AdjustmentEntryAuditStore',

        GeoStateStore: 'GeoStateStore',
        WageAttachmentOrderedAmountTypeStore:
            'WageAttachmentOrderedAmountTypeStore',
        AdvancePayTypeStore: 'AdvancePayTypeStore',
        DataEntryConfigurationStore: 'DataEntryConfigurationStore',
        CtsCodeStore: 'CtsCodeStore',
        CTSCodeStoreV2: 'CTSCodeStoreV2',
        LoadedPayrollEditSetStore: 'LoadedPayrollEditSetStore',
        ROEStateStore: 'ROEStateStore',
        ROEIssueReasonStore: 'ROEIssueReasonStore',
        WorkCertificateTypeStore: 'WorkCertificateTypeStore',
        EmployeeROERequestConfigStore: 'EmployeeROERequestConfigStore',
        EmployeeP45RequestConfigStore: 'EmployeeP45RequestConfigStore',
        EmployeeWorkCertificateRequestConfigStore:
            'EmployeeWorkCertificateRequestConfigStore',
        EmployeeWorkCertificateStore: 'EmployeeWorkCertificateStore',
        EmployeeROEStore: 'EmployeeROEStore',
        ROEEntryStore: 'ROEEntryStore',
        P45EntryStore: 'P45EntryStore',
        WorkCertificateEntryStore: 'WorkCertificateEntryStore',
        ROEEntryCacheStore: 'ROEEntryCacheStore',
        ROEDetailLoader: 'ROEDetailLoader',
        P45DetailLoader: 'P45DetailLoader',
        SOEDetailLoader: 'SOEDetailLoader',
        WorkCertificateDetailLoader: 'WorkCertificateDetailLoader',
        ROEClientContacts: 'ROEClientContacts',
        ROEPayGroupROEDetails: 'ROEPayGroupROEDetails',
        ROEMultipleRequestConfiguration: 'ROEMultipleRequestConfiguration',
        P45MultipleRequestConfiguration: 'P45MultipleRequestConfiguration',
        ROERecall: 'ROERecall',
        ROEVacationPayReason: 'ROEVacationPayReason',
        ROEOtherMonie: 'ROEOtherMonie',
        ROESpecialPaymentType: 'ROESpecialPaymentType',
        EmployeeHistoricalROEStore: 'EmployeeHistoricalROEStore',
        PayRunStore: 'PayRunStore',
        SOEEntryStore: 'SOEEntryStore',

        LegalEntityPayrollPreviewStore: 'LegalEntityPayrollPreviewStore',
        EmployeePayrollPreviewStore: 'EmployeePayrollPreviewStore',

        ContextPriorPeriodPayRunStore: 'ContextPriorPeriodPayRunStore',
        PayClassStore: 'PayClassStore',
        PayTypeStore: 'PayTypeStore',
        TaxabilityTypeStore: 'TaxabilityTypeStore',
        TaxComplianceStore: 'TaxComplianceStore',
        PayrollTaxTypeStore: 'TaxTypeStore',
        PayrollTaxStore: 'TaxNameStore',
        LegalEntityPRMStore: 'LegalEntityPRMStore',
        DeductionTaxTypeStore: 'DeductionTaxTypeStore',
        LaborMetricsStore: 'LaborMetricsStore',
        FilterDataEntryImportStore: 'FilterDataEntryImportStore',
        FilterCheckEntryImportStore: 'FilterCheckEntryImportStore',
        FilterAdjustmentEntryImportStore: 'FilterAdjustmentEntryImportStore',

        FilterDepartmentStore: 'FilterDepartmentStore',
        FilterJobStore: 'FilterJobStore',
        FilterPositionStore: 'FilterPositionStore',
        ThirdPartySickPayProviderStore: 'ThirdPartySickPayProviderStore',
        ThirdPartySickPayTaxExemptionStore:
            'ThirdPartySickPayTaxExemptionStore',
        FilterArchivedReportReportNameStore:
            'FilterArchivedReportReportNameStore',
        FilterArchivedReportSourceDeliveryPackageStore:
            'FilterArchivedReportSourceDeliveryPackageStore',
        FilterSaveByStoreAdjustment: 'FilterSaveByStoreAdjustment',
        FilterSaveByStoreCheck: 'FilterSaveByStoreCheck',
        FilterSaveByStoreQuickEntry: 'FilterSaveByStoreQuickEntry',
        FilterSaveByStoreImportQuickEntry: 'FilterSaveByStoreImportQuickEntry',
        StagingImportSetIdStore: 'StagingImportSetIdStore',
        prniletterSearchStore: 'prniletterSearchStore',
        PayRunResultsStore: 'payRunResultsStore',
        PayRunResultsStoreSummary: 'payRunResultsStoreSummary',

        FilterValidationStatusStore: 'FilterValidationStatusStore',
        FilterApprovalStatusStore: 'FilterApprovalStatusStore',
        FilterCreatedByStore: 'FilterCreatedByStore',
        FilterSavedByStoreImportQuickEntry:
            'FilterSavedByStoreImportQuickEntry',
        FilterImportSetStore: 'FilterImportSetStore',
        FilterApprovableImportStore: 'FilterApprovableImportStore',
        FilterPayrollElectionImportStore: 'FilterPayrollElectionImportStore',

        SOEEmployeeSearchStore: 'SOEEmployeeSearchStore',
        SOEEmployeeNumberSearchStore: 'SOEEmployeeNumberSearchStore',
        ODPEmployeeSearchStoreFullDisplayName:
            'ODPEmployeeSearchStoreFullDisplayName',
        EmployeeSOERequestConfigStore: 'EmployeeSOERequestConfigStore',

        BusinessOwnerGroupStore: 'BusinessOwnerGroupStore',
        DFWalletInfoStore: 'DFWalletInfoStore',
        TaxWageTypeStore: 'TaxWageTypeStore',
        IncomeWithholdingImportStatusStore:
            'IncomeWithholdingImportStatusStore',
    },

    PayEntryActivity: {
        AllColumns: 'ALL_COLUMNS',
        EarningsException: 'EARNINGS_EXCEPTION',
        TimeEntry: 'TIME_ENTRY',
        RetroTimeEntry: 'RETRO_TIME_ENTRY',
        DeductionOverrides: 'DEDUCTION_OVERRIDES',
        PositionEntry: 'POSITION_ENTRY',
        GarnishmentEntry: 'GARNISHMENT_ENTRY',
        SystemRetroEntry: 'SYSTEM_RETRO_ENTRY',
    },

    GridColumnStyle: {
        visible: 'display: table-cell;',
        hidden: 'display: none;',
    },

    TimeDataSource: {
        InternalWFM: '[INTERNAL WFM]',
        ExternalWFM: '[NON-WFM DATA]',
    },

    ValidationSourceType: {
        MyPay: 'MyPay',
        PayrollEngine: 'PayrollEngine',
        POSCommit: 'POSCommit',
        POSPublish: 'POSPublish',
        QuickEntry: 'PayrollQuickEntry',
        QuickEntryNew: 'PayrollQuickEntryNew',
        Check: 'PayrollChecks',
        Adjustment: 'PayrollPriorPeriodAdjustments',
        EditSet: 'EditSet',
        ROE: 'PayrollROEEntry',
        ROEHeader: 'ROEHeader',
        ROEDetail: 'ROEDetail',
        WorkCertificate: 'WorkCertificate',
        WorkCertificateHeader: 'WorkCertificateHeader',
        WorkCertificateDetail: 'WorkCertificateDetail',
        TimeData: 'PayrollTimeData',
        WageAndTax: 'WageAndTax',
        P45Header: 'P45Header',
        P45Detail: 'P45Detail',
        SOEHeader: 'SOEHeader',
    },

    TimeDataGroupBy: {
        None: 0,
        Retro: 1,
        BusinessDate: 2,
    },

    SupplmentalTaxationConstants: {
        CODE_NAME_SUPPLEMENTAL_FLAT_RATE: 'SupplementalFlatRate',
        CODE_NAME_SUPPLEMENTAL_SEPARATE_AGGREGATION: 'SupplementalSepAggr',
        CODE_NAME_SUPPLEMENTAL_SYSTEM_SELECTED: 'SupplementalSystemSelected',
        CODE_NAME_SUPPLEMENTAL_CUMULATIVE_METHOD:
            'SupplementalCumulativeMethod',
        CODE_NAME_PR_CHRISTMAS_BONUS_METHOD: 'ChristmasBonus',
        CODE_NAME_SUPPLEMENTAL_RATE_TABLE: 'SupplementalRateTable',
    },

    AdjustmentBatchProperty: {
        EXCLUDE_DISBURSE_DIRECT_DEPOSIT: 'EXCLUDE_DISBURSE_DIRECT_DEPOSIT',
        EXCLUDE_DISBURSE_PAYCARD: 'EXCLUDE_DISBURSE_PAYCARD',
        DISBURSE_FULL_NET_ONLY: 'DISBURSE_FULL_NET_ONLY',
        USA_TAXATION_PAYMENT_TYPE: 'USA_TAXATION_PAYMENT_TYPE',
        USA_TAXATION_PAY_FREQUENCY: 'USA_TAXATION_PAY_FREQUENCY',
        RESIDENCE_LOCATION: 'RESIDENCE_LOCATION',
        EXCLUDE_ADDITIONAL_TAX_AMOUNTS_US: 'EXCLUDE_ADDITIONAL_TAX_AMOUNTS_US',
        EXCLUDE_ADDITIONAL_TAX_AMOUNTS_CAN:
            'EXCLUDE_ADDITIONAL_TAX_AMOUNTS_CAN',
        CHECK_EMPLOYMENT_TYPE: 'CHECK_EMPLOYMENT_TYPE',
        CHECK_DISTRIBUTION_CODE: 'CHECK_DISTRIBUTION_CODE',
        CHECK_ADDRESS: 'CHECK_ADDRESS',
    },

    EmploymentTypeCode: {
        Contractor: 'Contractor',
        Pensioner: 'Pensioner',
        Employee: 'Employee',
    },

    SavedByStoreOption: {
        QuickEntry: 1,
        Check: 2,
        Adjustment: 3,
        None: 0,
    },

    EmploymentTypeId: {
        Contractor: '1',
        Pensioner: '2',
        Employee: '3',
    },

    RecalcStatus: {
        NotStarted: 0,
        InProcess: 1,
        Completed: 2,
        Stalled: 3,
        Blocked: 4,
    },

    PrintStatus: {
        SUCCESSED: 'SUCCESSED',
        FAIL: 'FAIL',
        INPROCESS: 'INPROCESS',
    },

    PrintStatusState: {
        NONE: 1,
        INPROCESS: 3,
    },

    MoveROEMode: {
        SELECTED: 'SELECTED',
        ALL: 'ALL',
    },

    ThirdPartySickPayEntryType: {
        EmployeeEarning: 'ThirdPartySickPayEmployeeEarning',
        EmployeeTax: 'ThirdPartySickPayEmployeeTax',
        EmployerTax: 'ThirdPartySickPayEmployerTax',
    },

    PayrollArchivedReportFilterMode: {
        PayPeriod: 1,
        PayDateRange: 2,
    },

    StopPaymentState: {
        SUCCESS: 'SUCCESS',
        FAILURE: 'FAILURE',
        IN_PROGRESS: 'IN_PROGRESS',
    },

    StopPaymentColumnField: {
        PayeeName: 'PayeeName',
        EmployeeNumber: 'EmployeeNumber',
        PayRunDisplayName: 'PayRunDisplayName',
        PayDate: 'PayDate',
        SequenceNumber: 'SequenceNumber',
        Amount: 'Amount',
        StopPaymentAction: 'StopPaymentAction',
        StopPaymentState: 'State',
        StopPaymentStateCode: 'StateCode',
        StopPaymentResponseType: 'ResponseType',
        TransactionTime: 'TransactionTime',
        LastModifiedUserName: 'LastModifiedUserName',
    },

    OnDemandColumnField: {
        EmployeeName: 'EmployeeName',
        EmployeeNumber: 'EmployeeNumber',
        CheckType: 'CheckType',
        EarningEffectiveStart: 'EarningEffectiveStart',
        EarningEffectiveEnd: 'EarningEffectiveEnd',
        State: 'CommitState',
        AvailableAmount: 'AvailableAmount',
        RequestedAmount: 'RequestedAmount',
        CheckDate: 'CheckDate',
        RequestedDateUTC: 'RequestedDateUTC',
        CommittedDateUTC: 'CommittedDateUTC',
        ReversedDate: 'ReversedDate',
        Comment: 'Comment',
        ProcessingState: 'ProcessingState',
        Source: 'Source',
    },

    PaymentsStatusColumnField: {
        Name: 'Name',
        EmployeeNumber: 'EmployeeNumber',
        TaxServiceID: 'TaxServiceID',
        LegalEntity: 'LegalEntity',
        PayRun: 'PayRun',
        PayDate: 'PayDate',
        CheckType: 'CheckType',
        PaymentType: 'PaymentType',
        PaymentNumber: 'PaymentNumber',
        BankName: 'BankName',
        RoutingNumber: 'RoutingNumber',
        AccountNumber: 'AccountNumber',
        Amount: 'Amount',
        PaymentStatus: 'PaymentStatus',
        LastStatusUpdateUTC: 'LastStatusUpdateUTC',
        NotificationType: 'NotificationType',
        NotificationReason: 'NotificationReason',
    },
    PaymentsStatusNotificationReasonColumnField: {
        CodeType: 'CodeType',
        Code: 'Code',
        CorrectValue: 'CorrectValue',
        InvalidField: 'InvalidField',
        InvalidValue: 'InvalidValue',
        ODFITraceNumber: 'ODFITraceNumber',
        Reason: 'Reason',
    },

    PaymentsStatusSystemGeneratedFavorites: {
        OutstandingChecks: 'Outstanding_Checks',
        ReturnedDirectDeposits: 'Returned_Direct_Deposits',
    },

    ExplanationStatementsSystemDescriptionConstants: {
        ApplySystemDescription: 'ApplySystemDescription',
        UseAsDefault: 'UseAsDefault',
        SectionTitleName: 'SectionTitleName',
        SystemDescription: 'SystemDescription',
        HasCustomDescription: 'HasCustomDescription',
    },

    AutoAdjustMode: {
        None: 0,
        MoveEIReferenceCode: 1,
    },

    WorkCertificateTypeCode: {
        Regular: 'REGULAR_WORK_CERTIFICATE',
        International: 'INTERNATIONAL_WORK_CERTIFICATE',
        Additional: 'ADDITIONAL_WORK_CERTIFICATE',
    },
    HourFieldMaxValue: 99999.999,
    AmountFieldMaxValue: 9999999999999.99999,
    OrderedPercentMaxValue: 100,
    DataEntryFormTextFieldSkeletonHeight: '77px',
    DataEntryFormTextAreaFieldSkeletonHeight: '162px',
    DataEntryFormCheckBoxFieldSkeletonHeight: '24px',
};
