export const EarningTypeConstants = {
    CODE_NAME_NORMAL: 'NORMAL',
    CODE_NAME_REIMBURSEMENT: 'REIMBURSEMENT',
    CODE_NAME_MEMO_CALC: 'MEMOCALC',
    CODE_NAME_TAXABLE_BENEFIT: 'TAXABLEBENEFIT',
};
