export const GeoStateData = [
    {
        GeoStateId: 1,
        StateCode: 'AL',
        CountryCode: 'USA',
        ShortName: 'Alabama',
    },
    { GeoStateId: 2, StateCode: 'AK', CountryCode: 'USA', ShortName: 'Alaska' },
    {
        GeoStateId: 3,
        StateCode: 'AZ',
        CountryCode: 'USA',
        ShortName: 'Arizona',
    },
    {
        GeoStateId: 4,
        StateCode: 'AR',
        CountryCode: 'USA',
        ShortName: 'Arkansas',
    },
    {
        GeoStateId: 5,
        StateCode: 'CA',
        CountryCode: 'USA',
        ShortName: 'California',
    },
    {
        GeoStateId: 6,
        StateCode: 'CO',
        CountryCode: 'USA',
        ShortName: 'Colorado',
    },
    {
        GeoStateId: 7,
        StateCode: 'CT',
        CountryCode: 'USA',
        ShortName: 'Connecticut',
    },
    {
        GeoStateId: 8,
        StateCode: 'DE',
        CountryCode: 'USA',
        ShortName: 'Delaware',
    },
    {
        GeoStateId: 9,
        StateCode: 'DC',
        CountryCode: 'USA',
        ShortName: 'District Of Columbia',
    },
    {
        GeoStateId: 10,
        StateCode: 'FL',
        CountryCode: 'USA',
        ShortName: 'Florida',
    },
    {
        GeoStateId: 11,
        StateCode: 'GA',
        CountryCode: 'USA',
        ShortName: 'Georgia',
    },
    {
        GeoStateId: 12,
        StateCode: 'HI',
        CountryCode: 'USA',
        ShortName: 'Hawaii',
    },
    { GeoStateId: 13, StateCode: 'ID', CountryCode: 'USA', ShortName: 'Idaho' },
    {
        GeoStateId: 14,
        StateCode: 'IL',
        CountryCode: 'USA',
        ShortName: 'Illinois',
    },
    {
        GeoStateId: 15,
        StateCode: 'IN',
        CountryCode: 'USA',
        ShortName: 'Indiana',
    },
    { GeoStateId: 16, StateCode: 'IA', CountryCode: 'USA', ShortName: 'Iowa' },
    {
        GeoStateId: 17,
        StateCode: 'KS',
        CountryCode: 'USA',
        ShortName: 'Kansas',
    },
    {
        GeoStateId: 18,
        StateCode: 'KY',
        CountryCode: 'USA',
        ShortName: 'Kentucky',
    },
    {
        GeoStateId: 19,
        StateCode: 'LA',
        CountryCode: 'USA',
        ShortName: 'Louisiana',
    },
    { GeoStateId: 20, StateCode: 'ME', CountryCode: 'USA', ShortName: 'Maine' },
    {
        GeoStateId: 21,
        StateCode: 'MD',
        CountryCode: 'USA',
        ShortName: 'Maryland',
    },
    {
        GeoStateId: 22,
        StateCode: 'MA',
        CountryCode: 'USA',
        ShortName: 'Massachusetts',
    },
    {
        GeoStateId: 23,
        StateCode: 'MI',
        CountryCode: 'USA',
        ShortName: 'Michigan',
    },
    {
        GeoStateId: 24,
        StateCode: 'MN',
        CountryCode: 'USA',
        ShortName: 'Minnesota',
    },
    {
        GeoStateId: 25,
        StateCode: 'MS',
        CountryCode: 'USA',
        ShortName: 'Mississippi',
    },
    {
        GeoStateId: 26,
        StateCode: 'MO',
        CountryCode: 'USA',
        ShortName: 'Missouri',
    },
    {
        GeoStateId: 27,
        StateCode: 'MT',
        CountryCode: 'USA',
        ShortName: 'Montana',
    },
    {
        GeoStateId: 28,
        StateCode: 'NE',
        CountryCode: 'USA',
        ShortName: 'Nebraska',
    },
    {
        GeoStateId: 29,
        StateCode: 'NV',
        CountryCode: 'USA',
        ShortName: 'Nevada',
    },
    {
        GeoStateId: 30,
        StateCode: 'NH',
        CountryCode: 'USA',
        ShortName: 'New Hampshire',
    },
    {
        GeoStateId: 31,
        StateCode: 'NJ',
        CountryCode: 'USA',
        ShortName: 'New Jersey',
    },
    {
        GeoStateId: 32,
        StateCode: 'NM',
        CountryCode: 'USA',
        ShortName: 'New Mexico',
    },
    {
        GeoStateId: 33,
        StateCode: 'NY',
        CountryCode: 'USA',
        ShortName: 'New York',
    },
    {
        GeoStateId: 34,
        StateCode: 'NC',
        CountryCode: 'USA',
        ShortName: 'North Carolina',
    },
    {
        GeoStateId: 35,
        StateCode: 'ND',
        CountryCode: 'USA',
        ShortName: 'North Dakota',
    },
    { GeoStateId: 36, StateCode: 'OH', CountryCode: 'USA', ShortName: 'Ohio' },
    {
        GeoStateId: 37,
        StateCode: 'OK',
        CountryCode: 'USA',
        ShortName: 'Oklahoma',
    },
    {
        GeoStateId: 38,
        StateCode: 'OR',
        CountryCode: 'USA',
        ShortName: 'Oregon',
    },
    {
        GeoStateId: 39,
        StateCode: 'PA',
        CountryCode: 'USA',
        ShortName: 'Pennsylvania',
    },
    {
        GeoStateId: 40,
        StateCode: 'RI',
        CountryCode: 'USA',
        ShortName: 'Rhode Island',
    },
    {
        GeoStateId: 41,
        StateCode: 'SC',
        CountryCode: 'USA',
        ShortName: 'South Carolina',
    },
    {
        GeoStateId: 42,
        StateCode: 'SD',
        CountryCode: 'USA',
        ShortName: 'South Dakota',
    },
    {
        GeoStateId: 43,
        StateCode: 'TN',
        CountryCode: 'USA',
        ShortName: 'Tennessee',
    },
    { GeoStateId: 44, StateCode: 'TX', CountryCode: 'USA', ShortName: 'Texas' },
    { GeoStateId: 45, StateCode: 'UT', CountryCode: 'USA', ShortName: 'Utah' },
    {
        GeoStateId: 46,
        StateCode: 'VT',
        CountryCode: 'USA',
        ShortName: 'Vermont',
    },
    {
        GeoStateId: 47,
        StateCode: 'VA',
        CountryCode: 'USA',
        ShortName: 'Virginia',
    },
    {
        GeoStateId: 48,
        StateCode: 'WA',
        CountryCode: 'USA',
        ShortName: 'Washington',
    },
    {
        GeoStateId: 49,
        StateCode: 'WV',
        CountryCode: 'USA',
        ShortName: 'West Virginia',
    },
    {
        GeoStateId: 50,
        StateCode: 'WI',
        CountryCode: 'USA',
        ShortName: 'Wisconsin',
    },
    {
        GeoStateId: 51,
        StateCode: 'WY',
        CountryCode: 'USA',
        ShortName: 'Wyoming',
    },
    {
        GeoStateId: 65,
        StateCode: 'PR',
        CountryCode: 'USA',
        ShortName: 'Puerto Rico',
    },
    {
        GeoStateId: 66,
        StateCode: 'AS',
        CountryCode: 'USA',
        ShortName: 'American Samoa',
    },
    {
        GeoStateId: 67,
        StateCode: 'FM',
        CountryCode: 'USA',
        ShortName: 'Federated States of Micronesia',
    },
    { GeoStateId: 68, StateCode: 'GU', CountryCode: 'USA', ShortName: 'Guam' },
    {
        GeoStateId: 69,
        StateCode: 'MH',
        CountryCode: 'USA',
        ShortName: 'Marshall Islands',
    },
    {
        GeoStateId: 70,
        StateCode: 'MP',
        CountryCode: 'USA',
        ShortName: 'Northern Mariana Islands',
    },
    { GeoStateId: 71, StateCode: 'PW', CountryCode: 'USA', ShortName: 'Palau' },
    {
        GeoStateId: 72,
        StateCode: 'VI',
        CountryCode: 'USA',
        ShortName: 'Virgin Islands',
    },
    {
        GeoStateId: 60,
        StateCode: 'AB',
        CountryCode: 'CAN',
        ShortName: 'Alberta',
    },
    {
        GeoStateId: 57,
        StateCode: 'BC',
        CountryCode: 'CAN',
        ShortName: 'British Columbia',
    },
    {
        GeoStateId: 56,
        StateCode: 'MB',
        CountryCode: 'CAN',
        ShortName: 'Manitoba',
    },
    {
        GeoStateId: 55,
        StateCode: 'NB',
        CountryCode: 'CAN',
        ShortName: 'New Brunswick',
    },
    {
        GeoStateId: 61,
        StateCode: 'NL',
        CountryCode: 'CAN',
        ShortName: 'Newfoundland and Labrador',
    },
    {
        GeoStateId: 62,
        StateCode: 'NT',
        CountryCode: 'CAN',
        ShortName: 'Northwest Territories',
    },
    {
        GeoStateId: 54,
        StateCode: 'NS',
        CountryCode: 'CAN',
        ShortName: 'Nova Scotia',
    },
    {
        GeoStateId: 64,
        StateCode: 'NU',
        CountryCode: 'CAN',
        ShortName: 'Nunavut',
    },
    {
        GeoStateId: 52,
        StateCode: 'ON',
        CountryCode: 'CAN',
        ShortName: 'Ontario',
    },
    {
        GeoStateId: 58,
        StateCode: 'PE',
        CountryCode: 'CAN',
        ShortName: 'Prince Edward Island',
    },
    {
        GeoStateId: 53,
        StateCode: 'QC',
        CountryCode: 'CAN',
        ShortName: 'Quebec',
    },
    {
        GeoStateId: 59,
        StateCode: 'SK',
        CountryCode: 'CAN',
        ShortName: 'Saskatchewan',
    },
    { GeoStateId: 63, StateCode: 'YT', CountryCode: 'CAN', ShortName: 'Yukon' },
];
