export const PayrollReasonConstants = {
    CODE_NAME_ADJUSTMENT_CORRECTION: 'ADJUSTMENT_CORRECTION',
    CODE_NAME_BONUS: 'BONUS',
    CODE_NAME_COMMISSION: 'COMMISSION',
    CODE_NAME_ENTITLEMENT_PAYOUT: 'ENTITLEMENT_PAYOUT',
    CODE_NAME_MISSED_PAY: 'MISSED_PAY',
    CODE_NAME_REFUND: 'REFUND',
    CODE_NAME_RETRO_PAY: 'RETRO_PAY',
    CODE_NAME_ROE: 'ROE',
    CODE_NAME_STOCK_OPTIONS: 'STOCK_OPTIONS',
    CODE_NAME_TERMINATION: 'TERMINATION',
    CODE_NAME_VOID: 'VOID',
};
