export const PreviewTypeConstants = {
    EARNINGS: 'Earnings',
    PRE_TAX_DEDUCTIONS: 'PreTaxDeductions',
    EMPLOYEE_TAX: 'EmployeeTaxes',
    POST_TAX_DEDUCTIONS: 'PostTaxDeductions',
    NET_PAY: 'NetPay',
    TAXABLE_BENEFITS: 'TaxableBenefits',
    MEMOCALC: 'MemoCalcs',
    EMPLOYER_TAX: 'EmployerTaxes',
    CHECK: 'Check',
    DIRECT_DEPOSIT: 'DirectDeposit',
    MANUAL: 'Manual',
    DISBURSEMENT_OTHER: 'DisbursementOther',
    ONDEMAND: 'OnDemand',
    PAYCARD: 'PayCard',
};

export const PreviewPaymentTypeConstants = {
    TOTAL_PAYMENTS: 'TotalPayments',
    TOTAL_IMPOUND: 'TotalImpound',
    NET_PAYROLL: 'NetPayroll',
    GARNISHMENT_IMPOUND: 'GarnishmentImpound',
    TAX_IMPOUND: 'TaxImpound',
    TAX_LIABILITY: 'TaxLiability',
    ADJUSTMENT: 'Adjustment',
    CUSTOMER_CHECKS_DEPOSITS: 'CustomerChecksDeposits',
    CUSTOMER_CHECKS: 'CustomerChecks',
    CUSTOMER_DIRECT_DEPOSITS: 'CustomerDirectDeposits',
    CUSTOMER_RESPONSIBLE_TAXES: 'CustomerResponsibleTaxes',
    CERIDIAN_CHECK: 'CeridianCheck',
    CERIDIAN_DIRECT_DEPOSIT: 'CeridianDirectDeposit',
    MANUAL_CHECKS: 'ManualChecks',
    ONSITE_CHECKS: 'OnsiteChecks',
    ONSITE_PAYROLL_CARDS: 'OnsitePayrollCards',
    VOID_CHECKS: 'VoidChecks',
    THIRD_PARTY_SICK_PAY: 'ThirdPartySickPay',
    ONDEMAND_PAY: 'OnDemandPay',
    CANADA_TEMP_WAGE_SUBSIDY: 'CanadaTempWageSubsidy',
    TAX_PAYMENT_DEFERRAL: 'TaxPaymentDeferral',
    ON_EHT_DEFERRAL_PENNY_OFFSET: 'ONEHTDeferralPennyOffset',
};
