export const UserPreferenceConstant = {
    EMPLOYEE_PANEL_MAXIMIZE_WINDOW: 'EMPLOYEE_PANEL_MAXIMIZE_WINDOW',
    NEVER_SHOW_QUICK_ENTRY_FORM_EDUCATION_BANNER:
        'NEVER_SHOW_QUICK_ENTRY_FORM_EDUCATION_BANNER',
    NEVER_SHOW_CHECK_HEADER_FORM_EDUCATION_BANNER:
        'NEVER_SHOW_CHECK_HEADER_FORM_EDUCATION_BANNER',
    NEVER_SHOW_CHECK_ENTRY_FORM_EDUCATION_BANNER:
        'NEVER_SHOW_CHECK_ENTRY_FORM_EDUCATION_BANNER',
    NEVER_SHOW_ADJUSTMENT_HEADER_FORM_EDUCATION_BANNER:
        'NEVER_SHOW_ADJUSTMENT_HEADER_FORM_EDUCATION_BANNER',
    NEVER_SHOW_ADJUSTMENT_ENTRY_FORM_EDUCATION_BANNER:
        'NEVER_SHOW_ADJUSTMENT_ENTRY_FORM_EDUCATION_BANNER',
};
