export const  payHolidays = [
    {
        payHolidayId: 408,
        holidayDate: '2024-01-01',
        isBankHoliday: true,
        shortName: "2024 New Year's Day (CAN)",
        xRefCode: '2024NewYearDayCAN',
        clientId: 0,
        payHolidayGroupId: 2,
        geoCountryId: 2,
        countryCode: 'CAN',
    },
    {
        payHolidayId: 409,
        holidayDate: '2024-01-01',
        isBankHoliday: true,
        shortName: "2024 New Year's Day (USA)",
        xRefCode: '2024NewYearDayUSA',
        clientId: 0,
        payHolidayGroupId: 1,
        geoCountryId: 1,
        countryCode: 'USA',
    },
    {
        payHolidayId: 412,
        holidayDate: '2024-01-15',
        isBankHoliday: true,
        shortName: '2024 Martin Luther King, Jr.Day',
        xRefCode: '2024MartinLutherKingDay',
        clientId: 0,
        payHolidayGroupId: 1,
        geoCountryId: 1,
        countryCode: 'USA',
    },
    {
        payHolidayId: 415,
        holidayDate: '2024-02-19',
        isBankHoliday: true,
        shortName: "2024 President's Birthday",
        xRefCode: '2024PresidentBirthday',
        clientId: 0,
        payHolidayGroupId: 1,
        geoCountryId: 1,
        countryCode: 'USA',
    },
    {
        payHolidayId: 418,
        holidayDate: '2024-05-27',
        isBankHoliday: true,
        shortName: '2024 Memorial Day',
        xRefCode: '2024MemorialDay',
        clientId: 0,
        payHolidayGroupId: 1,
        geoCountryId: 1,
        countryCode: 'USA',
    },
    {
        payHolidayId: 421,
        holidayDate: '2024-07-04',
        isBankHoliday: true,
        shortName: '2024 Independence Day',
        xRefCode: '2024IndependenceDay',
        clientId: 0,
        payHolidayGroupId: 1,
        geoCountryId: 1,
        countryCode: 'USA',
    },
    {
        payHolidayId: 424,
        holidayDate: '2024-09-02',
        isBankHoliday: true,
        shortName: '2024 Labor Day',
        xRefCode: '2024LaborDay',
        clientId: 0,
        payHolidayGroupId: 1,
        geoCountryId: 1,
        countryCode: 'USA',
    },
    {
        payHolidayId: 427,
        holidayDate: '2024-09-02',
        isBankHoliday: true,
        shortName: '2024 Labour Day',
        xRefCode: '2024LabourDay',
        clientId: 0,
        payHolidayGroupId: 2,
        geoCountryId: 2,
        countryCode: 'CAN',
    },
    {
        payHolidayId: 430,
        holidayDate: '2024-10-14',
        isBankHoliday: true,
        shortName: '2024 Columbus Day',
        xRefCode: '2024ColumbusDay',
        clientId: 0,
        payHolidayGroupId: 1,
        geoCountryId: 1,
        countryCode: 'USA',
    },
    {
        payHolidayId: 433,
        holidayDate: '2024-11-11',
        isBankHoliday: true,
        shortName: '2024 Veterans Day',
        xRefCode: '2024VeteransDay',
        clientId: 0,
        payHolidayGroupId: 1,
        geoCountryId: 1,
        countryCode: 'USA',
    },
    {
        payHolidayId: 436,
        holidayDate: '2024-11-28',
        isBankHoliday: true,
        shortName: '2024 Thanksgiving Day (USA)',
        xRefCode: '2024USAThanksgivingDay',
        clientId: 0,
        payHolidayGroupId: 1,
        geoCountryId: 1,
        countryCode: 'USA',
    },
    {
        payHolidayId: 439,
        holidayDate: '2024-12-25',
        isBankHoliday: true,
        shortName: '2024 Christmas Day (CAN)',
        xRefCode: '2024ChristmasDayCAN',
        clientId: 0,
        payHolidayGroupId: 2,
        geoCountryId: 2,
        countryCode: 'CAN',
    },
    {
        payHolidayId: 442,
        holidayDate: '2024-12-25',
        isBankHoliday: true,
        shortName: '2024 Christmas Day (USA)',
        xRefCode: '2024ChristmasDayUSA',
        clientId: 0,
        payHolidayGroupId: 1,
        geoCountryId: 1,
        countryCode: 'USA',
    },
    {
        payHolidayId: 445,
        holidayDate: '2024-03-29',
        isBankHoliday: true,
        shortName: '2024 Good Friday',
        xRefCode: '2024GoodFriday',
        clientId: 0,
        payHolidayGroupId: 2,
        geoCountryId: 2,
        countryCode: 'CAN',
    },
    {
        payHolidayId: 448,
        holidayDate: '2024-05-20',
        isBankHoliday: true,
        shortName: '2024 Victoria Day',
        xRefCode: '2024VictoriaDay',
        clientId: 0,
        payHolidayGroupId: 2,
        geoCountryId: 2,
        countryCode: 'CAN',
    },
    {
        payHolidayId: 451,
        holidayDate: '2024-07-01',
        isBankHoliday: true,
        shortName: '2024 Canada Day',
        xRefCode: '2024CanadaDay',
        clientId: 0,
        payHolidayGroupId: 2,
        geoCountryId: 2,
        countryCode: 'CAN',
    },
    {
        payHolidayId: 454,
        holidayDate: '2024-08-05',
        isBankHoliday: true,
        shortName: '2024 Civic Holiday',
        xRefCode: '2024CivicHoliday',
        clientId: 0,
        payHolidayGroupId: 2,
        geoCountryId: 2,
        countryCode: 'CAN',
    },
    {
        payHolidayId: 457,
        holidayDate: '2024-10-14',
        isBankHoliday: true,
        shortName: '2024 Thanksgiving Day (CAN)',
        xRefCode: '2024CanadianThanksgivingDay',
        clientId: 0,
        payHolidayGroupId: 2,
        geoCountryId: 2,
        countryCode: 'CAN',
    },
    {
        payHolidayId: 460,
        holidayDate: '2024-11-11',
        isBankHoliday: true,
        shortName: '2024 Remembrance Day',
        xRefCode: '2024RemembranceDay',
        clientId: 0,
        payHolidayGroupId: 2,
        geoCountryId: 2,
        countryCode: 'CAN',
    },
    {
        payHolidayId: 463,
        holidayDate: '2024-12-26',
        isBankHoliday: true,
        shortName: '2024 Boxing Day',
        xRefCode: '2024BoxingDay',
        clientId: 0,
        payHolidayGroupId: 2,
        geoCountryId: 2,
        countryCode: 'CAN',
    },
    {
        payHolidayId: 635,
        holidayDate: '2024-09-30',
        isBankHoliday: true,
        shortName: '2024 Truth and Reconciliation Day(Can)',
        xRefCode: '2024CanadianTruthReconciliation',
        clientId: 0,
        payHolidayGroupId: 2,
        geoCountryId: 2,
        countryCode: 'CAN',
    },
    {
        payHolidayId: 636,
        holidayDate: '2025-09-30',
        isBankHoliday: true,
        shortName: '2025 Truth and Reconciliation Day(Can)',
        xRefCode: '2025CanadianTruthReconciliation',
        clientId: 0,
        payHolidayGroupId: 2,
        geoCountryId: 2,
        countryCode: 'CAN',
    },
    {
        payHolidayId: 714,
        holidayDate: '2025-01-01',
        isBankHoliday: true,
        shortName: "2025 New Year's Day (CAN)",
        xRefCode: '2025NewYearDayCAN',
        clientId: 0,
        payHolidayGroupId: 2,
        geoCountryId: 2,
        countryCode: 'CAN',
    },
    {
        payHolidayId: 715,
        holidayDate: '2025-01-01',
        isBankHoliday: true,
        shortName: "2025 New Year's Day (USA)",
        xRefCode: '2025NewYearDayUSA',
        clientId: 0,
        payHolidayGroupId: 1,
        geoCountryId: 1,
        countryCode: 'USA',
    },
    {
        payHolidayId: 716,
        holidayDate: '2025-01-20',
        isBankHoliday: true,
        shortName: '2025 Martin Luther King, Jr.Day',
        xRefCode: '2025MartinLutherKingDay',
        clientId: 0,
        payHolidayGroupId: 1,
        geoCountryId: 1,
        countryCode: 'USA',
    },
    {
        payHolidayId: 717,
        holidayDate: '2025-02-17',
        isBankHoliday: true,
        shortName: "2025 President's Birthday",
        xRefCode: '2025PresidentBirthday',
        clientId: 0,
        payHolidayGroupId: 1,
        geoCountryId: 1,
        countryCode: 'USA',
    },
    {
        payHolidayId: 718,
        holidayDate: '2025-05-26',
        isBankHoliday: true,
        shortName: '2025 Memorial Day',
        xRefCode: '2025MemorialDay',
        clientId: 0,
        payHolidayGroupId: 1,
        geoCountryId: 1,
        countryCode: 'USA',
    },
    {
        payHolidayId: 719,
        holidayDate: '2025-07-04',
        isBankHoliday: true,
        shortName: '2025 Independence Day',
        xRefCode: '2025IndependenceDay',
        clientId: 0,
        payHolidayGroupId: 1,
        geoCountryId: 1,
        countryCode: 'USA',
    },
    {
        payHolidayId: 720,
        holidayDate: '2025-09-01',
        isBankHoliday: true,
        shortName: '2025 Labor Day',
        xRefCode: '2025LaborDay',
        clientId: 0,
        payHolidayGroupId: 1,
        geoCountryId: 1,
        countryCode: 'USA',
    },
    {
        payHolidayId: 721,
        holidayDate: '2025-09-01',
        isBankHoliday: true,
        shortName: '2025 Labour Day',
        xRefCode: '2025LabourDay',
        clientId: 0,
        payHolidayGroupId: 2,
        geoCountryId: 2,
        countryCode: 'CAN',
    },
    {
        payHolidayId: 722,
        holidayDate: '2025-10-13',
        isBankHoliday: true,
        shortName: '2025 Columbus Day',
        xRefCode: '2025ColumbusDay',
        clientId: 0,
        payHolidayGroupId: 1,
        geoCountryId: 1,
        countryCode: 'USA',
    },
    {
        payHolidayId: 723,
        holidayDate: '2025-11-11',
        isBankHoliday: true,
        shortName: '2025 Veterans Day',
        xRefCode: '2025VeteransDay',
        clientId: 0,
        payHolidayGroupId: 1,
        geoCountryId: 1,
        countryCode: 'USA',
    },
    {
        payHolidayId: 724,
        holidayDate: '2025-11-27',
        isBankHoliday: true,
        shortName: '2025 Thanksgiving Day (USA)',
        xRefCode: '2025USAThanksgivingDay',
        clientId: 0,
        payHolidayGroupId: 1,
        geoCountryId: 1,
        countryCode: 'USA',
    },
    {
        payHolidayId: 725,
        holidayDate: '2025-12-25',
        isBankHoliday: true,
        shortName: '2025 Christmas Day (CAN)',
        xRefCode: '2025ChristmasDayCAN',
        clientId: 0,
        payHolidayGroupId: 2,
        geoCountryId: 2,
        countryCode: 'CAN',
    },
    {
        payHolidayId: 726,
        holidayDate: '2025-12-25',
        isBankHoliday: true,
        shortName: '2025 Christmas Day (USA)',
        xRefCode: '2025ChristmasDayUSA',
        clientId: 0,
        payHolidayGroupId: 1,
        geoCountryId: 1,
        countryCode: 'USA',
    },
    {
        payHolidayId: 727,
        holidayDate: '2025-04-18',
        isBankHoliday: true,
        shortName: '2025 Good Friday',
        xRefCode: '2025GoodFriday',
        clientId: 0,
        payHolidayGroupId: 2,
        geoCountryId: 2,
        countryCode: 'CAN',
    },
    {
        payHolidayId: 728,
        holidayDate: '2025-05-19',
        isBankHoliday: true,
        shortName: '2025 Victoria Day',
        xRefCode: '2025VictoriaDay',
        clientId: 0,
        payHolidayGroupId: 2,
        geoCountryId: 2,
        countryCode: 'CAN',
    },
    {
        payHolidayId: 729,
        holidayDate: '2025-07-01',
        isBankHoliday: true,
        shortName: '2025 Canada Day',
        xRefCode: '2025CanadaDay',
        clientId: 0,
        payHolidayGroupId: 2,
        geoCountryId: 2,
        countryCode: 'CAN',
    },
    {
        payHolidayId: 730,
        holidayDate: '2025-08-04',
        isBankHoliday: true,
        shortName: '2025 Civic Holiday',
        xRefCode: '2025CivicHoliday',
        clientId: 0,
        payHolidayGroupId: 2,
        geoCountryId: 2,
        countryCode: 'CAN',
    },
    {
        payHolidayId: 731,
        holidayDate: '2025-10-13',
        isBankHoliday: true,
        shortName: '2025 Thanksgiving Day (CAN)',
        xRefCode: '2025CanadianThanksgivingDay',
        clientId: 0,
        payHolidayGroupId: 2,
        geoCountryId: 2,
        countryCode: 'CAN',
    },
    {
        payHolidayId: 732,
        holidayDate: '2025-11-11',
        isBankHoliday: true,
        shortName: '2025 Remembrance Day',
        xRefCode: '2025RemembranceDay',
        clientId: 0,
        payHolidayGroupId: 2,
        geoCountryId: 2,
        countryCode: 'CAN',
    },
    {
        payHolidayId: 733,
        holidayDate: '2025-12-26',
        isBankHoliday: true,
        shortName: '2025 Boxing Day',
        xRefCode: '2025BoxingDay',
        clientId: 0,
        payHolidayGroupId: 2,
        geoCountryId: 2,
        countryCode: 'CAN',
    },
    {
        payHolidayId: 734,
        holidayDate: '2025-06-19',
        isBankHoliday: true,
        shortName: '2025 Juneteenth Day',
        xRefCode: '2025Juneteenth',
        clientId: 0,
        payHolidayGroupId: 1,
        geoCountryId: 1,
        countryCode: 'USA',
    },
    {
        payHolidayId: 737,
        holidayDate: '2024-06-19',
        isBankHoliday: true,
        shortName: '2024 Juneteenth Day',
        xRefCode: '2024Juneteenth',
        clientId: 0,
        payHolidayGroupId: 1,
        geoCountryId: 1,
        countryCode: 'USA',
    },
];
